window.MATH_CONTENT = {
  title: 'Matematika Kelas 3 Semester 1', storageKey: 'grade3MathSemester1',
  tagline: 'Memahami bilangan lebih besar, operasi, pecahan, dan pengukuran dengan strategi.',
  sourceNote: 'Pemetaan semester berbasis urutan pembelajaran dari CP/TP Kurikulum Merdeka Fase B; pembagian semester bukan pembagian resmi CP pemerintah.',
  chapters: [
    { id: 'bab-1', number: 1, world: 'DUNIA BILANGAN', title: 'Bilangan sampai 10.000', icon: '🔢', color: 'coral', goal: 'Membaca, mengurai, membandingkan, dan membulatkan bilangan.', subs: [
      { title: 'Nilai Tempat', concept: 'Menentukan nilai angka pada ribuan, ratusan, puluhan, dan satuan.', activity: { type: 'pattern', mode: 'input', visual: '4.582', prompt: 'Nilai angka 5 pada 4.582 adalah ...', answer: 500, choices: [5, 50, 500], instruction: 'Pecah bilangan menjadi ribuan, ratusan, puluhan, dan satuan.', hints: ['Angka 5 berada di tempat ratusan.', 'Satu ratusan bernilai seratus.'], explanation: 'Benar. Angka 5 berada di tempat ratusan, jadi nilainya 500.' } },
      { title: 'Bandingkan Ribuan', concept: 'Membandingkan bilangan dengan alasan nilai tempat.', activity: { type: 'compare', mode: 'strategy', visual: '3.850  •  3.580', prompt: 'Strategi yang paling membantu membandingkan kedua bilangan adalah ...', answer: 'Membandingkan ratusan', choices: ['Membandingkan ratusan', 'Melihat angka terakhir', 'Menjumlahkan semua angka'], instruction: 'Bandingkan nilai tempat dari kiri ke kanan.', hints: ['Kedua bilangan memiliki 3 ribuan.', 'Bandingkan angka ratusannya.'], explanation: 'Tepat. Setelah ribuannya sama, bandingkan angka ratusan.' } },
      { title: 'Bulatkan Puluhan', concept: 'Membulatkan bilangan ke puluhan terdekat.', activity: { type: 'pattern', mode: 'input', challenge: true, visual: '67 → ...', prompt: '67 dibulatkan ke puluhan terdekat menjadi ...', answer: 70, choices: [60, 67, 70], instruction: 'Perhatikan angka satuan untuk menentukan pembulatan.', hints: ['Angka satuannya adalah 7.', 'Jika satuan 5 atau lebih, bulatkan ke atas.'], explanation: 'Benar. Karena satuannya 7, 67 dibulatkan menjadi 70.' } }
    ] },
    { id: 'bab-2', number: 2, world: 'DUNIA OPERASI', title: 'Operasi Bilangan', icon: '➗', color: 'sun', goal: 'Menyelesaikan operasi campuran sederhana dengan urutan berpikir.', subs: [
      { title: 'Perkalian Bersusun', concept: 'Menghubungkan perkalian dengan kelompok sama banyak.', activity: { type: 'sum', mode: 'strategy', left: 4, right: 6, visual: '4 × 6', prompt: 'Strategi yang paling membantu mencari 4 × 6 adalah ...', answer: 'Membuat 4 kelompok berisi 6', choices: ['Membuat 4 kelompok berisi 6', 'Mengurangi 4 dari 6', 'Menjumlahkan 4 dan 6'], instruction: 'Bayangkan empat kelompok yang sama banyak.', hints: ['Perkalian berarti kelompok sama banyak.', 'Buat empat kelompok, masing-masing berisi enam.'], explanation: 'Benar. Empat kelompok berisi enam menghasilkan 24.' } },
      { title: 'Pembagian Sama Rata', concept: 'Menentukan hasil bagi dari kelompok yang sama.', activity: { type: 'difference', mode: 'input', left: 36, right: 6, visual: '36 ÷ 6', prompt: '36 ÷ 6 = ...', answer: 6, choices: [5, 6, 7], instruction: 'Bayangkan 36 benda dibagi rata kepada 6 kelompok.', hints: ['Cari bilangan yang jika dikali 6 menghasilkan 36.', '6 × 6 = 36.'], explanation: 'Tepat. Setiap kelompok mendapat 6.' } },
      { title: 'Dua Langkah', concept: 'Menyelesaikan masalah dengan dua operasi berurutan.', activity: { type: 'sum', mode: 'input', challenge: true, left: 25, right: 15, visual: '25 + 15 - 10', prompt: '25 + 15 - 10 = ...', answer: 30, choices: [20, 30, 40], instruction: 'Selesaikan operasi pertama, lalu gunakan hasilnya untuk operasi kedua.', hints: ['25 + 15 = 40.', 'Sekarang kurangi 10 dari 40.'], explanation: 'Hebat. Langkahnya 25 + 15 = 40, lalu 40 - 10 = 30.' } }
    ] },
    { id: 'bab-3', number: 3, world: 'DUNIA PECAHAN', title: 'Pecahan dan Kesetaraan', icon: '🍰', color: 'leaf', goal: 'Membandingkan dan menemukan pecahan sederhana yang setara.', subs: [
      { title: 'Pembilang dan Penyebut', concept: 'Membaca arti angka atas dan bawah pada pecahan.', activity: { type: 'pattern', mode: 'strategy', visual: '3/4', prompt: 'Cara membaca pecahan 3/4 yang tepat adalah ...', answer: 'Tiga per empat', choices: ['Tiga per empat', 'Empat per tiga', 'Tiga ditambah empat'], instruction: 'Angka atas dibaca lebih dulu, lalu angka bawah.', hints: ['Angka atas disebut pembilang.', '3/4 dibaca tiga per empat.'], explanation: 'Benar. 3/4 dibaca tiga per empat.' } },
      { title: 'Pecahan Senilai', concept: 'Menemukan pecahan yang menunjukkan bagian sama.', activity: { type: 'compare', mode: 'strategy', visual: '1/2  =  2/4', prompt: 'Mengapa 1/2 dan 2/4 senilai?', answer: 'Menunjukkan bagian yang sama', choices: ['Menunjukkan bagian yang sama', 'Penyebutnya selalu sama', 'Angkanya dijumlahkan'], instruction: 'Bayangkan satu benda dibagi menjadi bagian yang sama besar.', hints: ['Satu dari dua bagian sama luasnya dengan dua dari empat bagian.', 'Lihat luas bagian, bukan hanya angkanya.'], explanation: 'Tepat. Kedua pecahan menunjukkan bagian yang sama dari keseluruhan.' } },
      { title: 'Bandingkan Pecahan', concept: 'Membandingkan pecahan berpenyebut sama.', activity: { type: 'compare', mode: 'input', challenge: true, visual: '2/5  •  4/5', prompt: 'Pecahan yang lebih besar adalah ...', answer: '4/5', choices: ['2/5', '4/5', 'Sama'], instruction: 'Tulis pecahan yang pembilangnya lebih besar.', hints: ['Penyebut kedua pecahan sama-sama 5.', 'Bandingkan pembilang 2 dan 4.'], explanation: 'Benar. Dengan penyebut sama, pembilang 4 menunjukkan bagian lebih banyak.' } }
    ] },
    { id: 'bab-4', number: 4, world: 'DUNIA UKURAN', title: 'Keliling dan Luas Awal', icon: '📐', color: 'sky', goal: 'Mengukur panjang sisi dan memahami keliling sebagai jumlah sisi.', subs: [
      { title: 'Keliling Persegi', concept: 'Menjumlahkan empat sisi yang sama panjang.', activity: { type: 'sum', mode: 'input', left: 6, right: 6, visual: '6 + 6 + 6 + 6', prompt: 'Keliling persegi sisi 6 cm adalah ...', answer: 24, choices: [12, 24, 36], instruction: 'Keliling adalah jumlah semua sisi.', hints: ['Ada empat sisi yang masing-masing 6 cm.', 'Hitung 6 + 6 + 6 + 6.'], explanation: 'Benar. Kelilingnya 24 cm.' } },
      { title: 'Keliling Persegi Panjang', concept: 'Menjumlahkan dua panjang dan dua lebar.', activity: { type: 'sum', mode: 'strategy', left: 8, right: 4, visual: '8 + 4 + 8 + 4', prompt: 'Strategi yang tepat untuk keliling persegi panjang adalah ...', answer: 'Menjumlahkan p + l + p + l', choices: ['Menjumlahkan p + l + p + l', 'Mengalikan p dan l', 'Menjumlahkan p + l saja'], instruction: 'Perhatikan bahwa persegi panjang memiliki dua panjang dan dua lebar.', hints: ['Sisi yang berhadapan sama panjang.', 'Gunakan 8 + 4 + 8 + 4.'], explanation: 'Tepat. Keliling adalah panjang + lebar + panjang + lebar.' } },
      { title: 'Luas dengan Satuan', concept: 'Menghitung banyak persegi satuan yang menutupi bidang.', activity: { type: 'count', mode: 'input', challenge: true, items: '■', display: 12, visual: '3 × 4 persegi satuan', prompt: 'Luas bidang 3 baris dan 4 kolom adalah ...', answer: 12, choices: [7, 12, 14], instruction: 'Hitung persegi satuan pada baris dan kolom.', hints: ['Ada 3 baris dengan 4 persegi pada setiap baris.', 'Gunakan 3 × 4.'], explanation: 'Benar. Ada 12 persegi satuan yang menutupi bidang.' } }
    ] },
    { id: 'bab-5', number: 5, world: 'DUNIA DATA', title: 'Data dan Diagram', icon: '📊', color: 'violet', goal: 'Mengumpulkan, menyajikan, dan menafsirkan data sederhana.', subs: [
      { title: 'Baca Diagram Batang', concept: 'Membandingkan tinggi batang pada diagram.', activity: { type: 'compare', mode: 'strategy', visual: 'Merah ███  Biru █████', prompt: 'Bukti bahwa data biru lebih banyak adalah ...', answer: 'Batangnya lebih tinggi', choices: ['Batangnya lebih tinggi', 'Warnanya lebih cerah', 'Namanya lebih pendek'], instruction: 'Bandingkan tinggi batang, bukan warnanya.', hints: ['Batang yang lebih tinggi mewakili jumlah lebih banyak.', 'Batang biru mencapai lima tanda.'], explanation: 'Tepat. Tinggi batang menunjukkan banyaknya data.' } },
      { title: 'Selisih Data', concept: 'Menghitung selisih dua data.', activity: { type: 'difference', mode: 'input', left: 15, right: 9, visual: '15 − 9', prompt: 'Data A 15 dan data B 9. Selisihnya ...', answer: 6, choices: [5, 6, 7], instruction: 'Selisih berarti data yang lebih besar dikurangi data yang lebih kecil.', hints: ['Gunakan 15 − 9.', '15 dikurangi 9 sama dengan 6.'], explanation: 'Benar. Selisih data A dan B adalah 6.' } },
      { title: 'Tarik Kesimpulan', concept: 'Menjawab pertanyaan dengan bukti dari data.', activity: { type: 'pattern', mode: 'strategy', challenge: true, visual: 'Kucing 8  •  Ikan 5', prompt: 'Kesimpulan yang didukung data adalah ...', answer: 'Kucing dipilih lebih banyak', choices: ['Kucing dipilih lebih banyak', 'Ikan dipilih lebih banyak', 'Keduanya sama banyak'], instruction: 'Gunakan angka pada data sebagai bukti.', hints: ['Bandingkan 8 dan 5.', 'Angka 8 lebih besar daripada 5.'], explanation: 'Hebat. Data menunjukkan kucing dipilih lebih banyak.' } }
    ] }
  ]
};
