(() => {
  const content = window.GRADE1_INDO_CONTENT;
  const map = document.querySelector('#indo-map');
  const doneKey = (chapter, sub) => `grade1IndoDone:${chapter}:${sub}`;
  const completed = content.chapters.reduce((total, chapter) => total + chapter.subs.filter((_, index) => localStorage.getItem(doneKey(chapter.id, index)) === 'true').length, 0);
  const total = content.chapters.reduce((sum, chapter) => sum + chapter.subs.length, 0);
  let stars = Number(localStorage.getItem('grade1IndoStars') || 0);
  if (!Number.isFinite(stars) || stars < 0) stars = 0;
  document.querySelector('#starCount').textContent = stars;
  const first = content.chapters.find((chapter) => chapter.subs.some((_, index) => localStorage.getItem(doneKey(chapter.id, index)) !== 'true')) || content.chapters[0];
  map.innerHTML = `<aside class="side-nav" aria-label="Navigasi Bahasa Indonesia"><a class="side-link active" href="index.html" aria-current="page"><span>⌂</span>Beranda</a><a class="side-link" href="bab${first.number}.html"><span>📖</span>Materi</a><a class="side-link" href="bab${first.number}.html"><span>🎮</span>Permainan</a><a class="side-link" href="#achievements"><span>★</span>Prestasi</a><a class="side-link" href="#footer-note"><span>⚙</span>Pengaturan</a></aside><div class="dashboard-content"><section class="hero"><div class="hero-copy"><p class="eyebrow">BAHASA INDONESIA · PETUALANGAN LITERASI</p><h1>Aku Bisa<br><em>Membaca!</em></h1><p>Dengarkan, ucapkan, baca, dan tulis bersama teman belajar.</p><a class="cta" href="bab${first.number}.html"><span>▶</span> ${completed ? 'Lanjutkan Belajar' : 'Mulai Belajar'}</a></div><div class="hero-scene" aria-label="Ilustrasi anak belajar membaca"><span class="character-frame character-left"><img class="character-art" src="karakter1.png" alt="Anak perempuan dan kucing belajar membaca"></span><span class="character-frame character-right"><img class="character-art" src="karakter2.png" alt="Anak laki-laki belajar Bahasa Indonesia"></span></div></section><section class="learning-section" id="achievements"><div class="chapter-grid" aria-label="Empat materi Bahasa Indonesia">${content.chapters.map((chapter) => { const done = chapter.subs.filter((_, index) => localStorage.getItem(doneKey(chapter.id, index)) === 'true').length; return `<a class="chapter ${chapter.color}" href="bab${chapter.number}.html"><span class="chapter-icon">${chapter.icon}</span><small>MATERI 0${chapter.number}</small><h3>${chapter.title}</h3><p>${chapter.description}</p><div class="card-visual" aria-hidden="true">${['👋','🔤','✏️','🌳'][chapter.number - 1]}</div><b>${done}/${chapter.subs.length} submateri selesai <span>→</span></b></a>`; }).join('')}</div></section><section class="progress"><div class="progress-heading"><div><strong>Peta Belajar</strong></div><span>${completed} dari ${total} langkah selesai</span></div><div class="progress-track"><i style="width:${Math.round(completed / total * 100)}%"></i></div></section></div>`;
  const progress = map.querySelector('.progress');
  map.querySelector('.hero-copy').append(progress);
})();