window.MATH_LAB = {
  storageKey: 'grade6MathSemester1',
  title: 'Math Lab',
  labs: [
    { id: 'number-operations', code: '01', icon: '01', name: 'Lab Bilangan dan Operasi', color: 'amber', question: 'Bagaimana strategi operasi membantu mengambil keputusan?', badge: 'PENJELAJAH BILANGAN', challenge: { title: 'Pilih Strategi', prompt: 'Bandingkan operasi, analisis hubungan, dan pilih strategi yang paling masuk akal.' }, missions: [
      { id: 'ratio-scale', title: 'Skala dan Rasio', phase: 'ANALISIS', objective: 'Siswa dapat membedakan rasio dan menentukan skala yang sesuai.', type: 'choice', visual: '1:5', prompt: 'Jika 1 cm mewakili 5 m, maka 3 cm mewakili ... m.', choices: ['10 m', '15 m', '20 m'], answer: '15 m', explain: '3 × 5 = 15, jadi skala 1:5 menghasilkan 15 m.' },
      { id: 'compare-ratio', title: 'Bandingkan Rasio', phase: 'RENCANAKAN → VERIFIKASI', objective: 'Siswa dapat membandingkan dua rasio dan memeriksa hasilnya.', type: 'input', visual: '2:5 dan 4:10', prompt: 'Apakah kedua rasio tersebut ekuivalen? Jawab: ya atau tidak.', answer: 'ya', hint: 'Sederhanakan 4:10.', explain: '4:10 = 2:5, jadi keduanya ekuivalen.' }
    ] },
    { id: 'fraction-decimal-percent', code: '02', icon: '02', name: 'Lab Pecahan, Desimal, dan Persen', color: 'coral', question: 'Kapan pecahan, desimal, atau persen menjadi bentuk yang paling tepat?', badge: 'PENEMU STRATEGI', challenge: { title: 'Ubah Bentuk', prompt: 'Ubah bentuk, pilih strategi, dan buktikan hasilnya.' }, missions: [
      { id: 'fraction-decimal', title: 'Ubah ke Desimal', phase: 'ANALISIS', objective: 'Siswa dapat mengubah pecahan menjadi desimal dan membandingkan nilai.', type: 'choice', visual: '7/8 = ?', prompt: 'Hasilnya adalah ...', choices: ['0,875', '0,78', '0,85'], answer: '0,875', explain: '7 ÷ 8 = 0,875.' },
      { id: 'decimal-compare', title: 'Urutkan Nilai', phase: 'PECAHKAN → JELASKAN', objective: 'Siswa dapat mengurutkan desimal dengan alasan yang logis.', type: 'sequence', visual: '0,25; 0,5; 0,375', prompt: 'Urutkan dari yang terkecil ke terbesar.', choices: ['0,25', '0,375', '0,5'], answer: ['0,25', '0,375', '0,5'], explain: '0,25 < 0,375 < 0,5.' }
    ] },
    { id: 'ratio-proportion', code: '03', icon: '03', name: 'Lab Rasio dan Proporsi', color: 'blue', question: 'Bagaimana hubungan antarbesaran membantu menyelesaikan masalah?', badge: 'PENJELAJAH PROPORSI', challenge: { title: 'Hitung dan Buktikan', prompt: 'Pilih rasio, hitung hasil, dan tuliskan alasanmu.' }, missions: [
      { id: 'unit-conversion', title: 'Konversi Satuan', phase: 'RENCANAKAN', objective: 'Siswa dapat mengubah satuan panjang dan volume ke bentuk yang tepat.', type: 'choice', visual: '3,6 km = ... m', prompt: 'Hasil konversinya adalah ...', choices: ['360 m', '3600 m', '36000 m'], answer: '3600 m', explain: '1 km = 1000 m, jadi 3,6 × 1000 = 3600 m.' },
      { id: 'capacity-problem', title: 'Volume Berdasarkan Waktu', phase: 'PECAHKAN → VERIFIKASI', objective: 'Siswa dapat menghitung volume atau kapasitas dalam konteks nyata dan memeriksa jawaban.', type: 'input', visual: '2 liter setiap menit', prompt: 'Dalam 4 menit, air yang tertampung adalah ... liter.', answer: '8', hint: '2 × 4 = 8.', explain: 'Jumlah air bertambah 2 liter tiap menit.' }
    ] },
    { id: 'geometry-measurement', code: '04', icon: '04', name: 'Lab Geometri dan Pengukuran', color: 'violet', question: 'Apa yang berubah dan apa yang tetap pada bangun dan ukurannya?', badge: 'DETEKTIF GEOMETRI', challenge: { title: 'Rancang Bentuk', prompt: 'Pilih bangun yang sesuai, hitung ukuran, dan jelaskan alasanmu.' }, missions: [
      { id: 'perimeter-compare', title: 'Bandingkan Keliling', phase: 'ANALISIS', objective: 'Siswa dapat membandingkan keliling beberapa bentuk dan memilih bentuk optimal.', type: 'choice', visual: 'Persegi 8 cm dan persegi panjang 10 × 6', prompt: 'Bangun dengan keliling lebih besar adalah ...', choices: ['Persegi', 'Persegi panjang', 'Sama'], answer: 'Persegi', explain: 'Keliling persegi = 32, keliling persegi panjang = 32, sama.' },
      { id: 'area-composite', title: 'Luas Gabungan', phase: 'PECAHKAN → JELASKAN', objective: 'Siswa dapat menghitung luas bangun gabungan dan menjelaskan langkahnya.', type: 'input', visual: 'persegi 9 m dan persegi panjang 5 m × 3 m', prompt: 'Luas gabungan keduanya adalah ... m².', answer: '96', hint: '9² = 81, lalu 5 × 3 = 15, jumlahkan.', explain: '81 + 15 = 96 m².' }
    ] },
    { id: 'volume-solid', code: '05', icon: '05', name: 'Lab Volume dan Bangun Ruang', color: 'green', question: 'Bagaimana ukuran bangun ruang membantu merancang benda?', badge: 'PENJELAJAH BANGUN RUANG', challenge: { title: 'Membaca Ukuran', prompt: 'Hitung volume, pilih kesimpulan, dan jelaskan bukti.' }, missions: [
      { id: 'median-data', title: 'Median dan Modus', phase: 'ANALISIS', objective: 'Siswa dapat menganalisis data dengan median dan modus untuk menarik kesimpulan.', type: 'choice', visual: '10, 12, 14, 14, 18', prompt: 'Median dari data tersebut adalah ...', choices: ['10', '14', '18'], answer: '14', explain: 'Data terurut: 10, 12, 14, 14, 18; angka tengahnya adalah 14.' },
      { id: 'probability-case', title: 'Peluang Kejadian', phase: 'VERIFIKASI', objective: 'Siswa dapat menghitung peluang sederhana dan memeriksa apakah hasilnya masuk akal.', type: 'input', visual: '4 merah, 3 biru, 3 hijau', prompt: 'Peluang mengambil bola biru adalah ...', answer: '3/10', hint: 'Jumlah total bola = 10.', explain: 'Bola biru ada 3 dari 10 total.' }
    ] },
    { id: 'data-probability', code: '06', icon: '06', name: 'Lab Data dan Peluang', color: 'teal', question: 'Bagaimana data dan peluang membantu keputusan?', badge: 'DETEKTIF DATA', challenge: { title: 'Misi Integrasi', prompt: 'Interpretasikan data dan peluang untuk membuat keputusan terbaik.' }, missions: [
      { id: 'integrated-plan', title: 'Rencana Solusi', phase: 'RENCANAKAN', objective: 'Siswa dapat menentukan langkah-langkah yang benar untuk memecahkan masalah gabungan.', type: 'choice', visual: 'Pembelian 3 buku seharga 45.000', prompt: 'Biaya satu buku adalah ...', choices: ['10.000', '15.000', '20.000'], answer: '15.000', explain: '45.000 ÷ 3 = 15.000.' },
      { id: 'integrated-check', title: 'Periksa Jawaban', phase: 'VERIFIKASI → JELASKAN', objective: 'Siswa dapat mengecek kebenaran jawaban dengan membuktikan alasan logisnya.', type: 'input', visual: '1/4 dari 80 = ...', prompt: 'Hasilnya adalah ...', answer: '20', hint: '80 dibagi 4.', explain: '1/4 dari 80 sama dengan 20.' }
    ] }
  ]
};