window.MATH_LAB = {
  storageKey: 'grade4MathSemester2',
  title: 'Matematika Kelas 4 SD · Semester 2',
  labs: [
    { id: 'fraction', code: '01', icon: '01', name: 'Lab Pecahan', color: 'coral', question: 'Bagaimana pecahan membantu kita membandingkan bagian dari keseluruhan?', badge: 'PENJELAJAH PECAHAN', challenge: { title: 'Bangun Kue Pecahan', prompt: 'Bandingkan, gabungkan, dan jelaskan pecahan dalam masalah nyata.' }, missions: [
      { id: 'place-value-2', title: 'Bongkar Nilai Tempat', phase: 'AMATI', objective: 'Siswa dapat membedakan nilai tempat dan menyusun bilangan berdasarkan konteks.', type: 'choice', visual: '12.345.678', prompt: 'Angka 3 pada bilangan 12.345.678 memiliki nilai ...', choices: ['3 juta', '300 ribu', '30 ribu'], answer: '300 ribu', explain: 'Digit 3 berada pada tempat ratus ribuan, sehingga nilainya 300.000.' },
      { id: 'compare-round', title: 'Bandingkan dan Bulatkan', phase: 'COBA → TEMUKAN', objective: 'Siswa dapat membandingkan bilangan dan membulatkan ke nilai tempat tertentu.', type: 'input', visual: '4.678 → 4.700', prompt: 'Bilangan 4.678 dibulatkan ke ratusan terdekat adalah ...', answer: '4700', hint: 'Perhatikan angka puluhan: 7 membuat dibulatkan ke atas.', explain: 'Karena 7 > 5, 4.678 dibulatkan menjadi 4.700.' }
    ] },
    { id: 'decimal', code: '02', icon: '02', name: 'Lab Desimal', color: 'blue', question: 'Bagaimana desimal membantu membandingkan ukuran dan nilai?', badge: 'PENJELAJAH DESIMAL', challenge: { title: 'Tantangan Desimal', prompt: 'Hubungkan pecahan, desimal, dan situasi sehari-hari.' }, missions: [
      { id: 'multi-step', title: 'Soal Dua Langkah', phase: 'AMATI → COBA', objective: 'Siswa dapat menyelesaikan soal dua langkah dan memilih operasi yang tepat.', type: 'choice', visual: '24 × 3 + 18', prompt: 'Hasil operasi ini adalah ...', choices: ['90', '66', '74'], answer: '90', explain: '24 × 3 = 72, lalu 72 + 18 = 90.' },
      { id: 'error-analysis', title: 'Temukan Kesalahan', phase: 'PECAHKAN → JELASKAN', objective: 'Siswa dapat menganalisis alasan kesalahan operasi dan memperbaiki hasilnya.', type: 'error', visual: '468 ÷ 3 = 156', prompt: 'Apakah perhitungan tersebut benar?', choices: ['Benar', 'Salah'], answer: 'Benar', hint: 'Coba 156 × 3', explain: '156 × 3 = 468, sehingga jawabannya benar.' }
    ] },
    { id: 'perimeter-area', code: '03', icon: '03', name: 'Lab Keliling dan Luas', color: 'green', question: 'Bagaimana ukuran sisi menentukan keliling dan luas?', badge: 'PENJELAJAH UKURAN', challenge: { title: 'Desain Taman', prompt: 'Hitung keliling dan luas untuk memilih desain yang tepat.' }, missions: [
      { id: 'equivalent-fraction', title: 'Pecahan Senilai', phase: 'TEMUKAN', objective: 'Siswa dapat mengenali pecahan senilai dalam bentuk visual dan angka.', type: 'choice', visual: '1/2 = ?', prompt: 'Pecahan yang senilai dengan 1/2 adalah ...', choices: ['3/5', '2/4', '1/3'], answer: '2/4', explain: 'Dua perempat sama besar dengan setengah.' },
      { id: 'compare-fraction', title: 'Membandingkan Pecahan', phase: 'JELASKAN', objective: 'Siswa dapat mengurutkan pecahan berdasarkan ukuran dan membenarkan alasan.', type: 'sequence', visual: '0 ───────── 1', prompt: 'Urutkan dari yang terkecil ke terbesar.', choices: ['1/3', '2/5', '3/4'], answer: ['1/3', '2/5', '3/4'], explain: 'Pada garis bilangan, semakin ke kanan nilainya semakin besar.' }
    ] },
    { id: 'angle-geometry', code: '04', icon: '04', name: 'Lab Sudut dan Geometri', color: 'violet', question: 'Bagaimana sudut dan sifat bangun membantu memecahkan masalah?', badge: 'DETEKTIF GEOMETRI', challenge: { title: 'Buru Sudut', prompt: 'Kenali sudut, klasifikasikan bangun, dan jelaskan sifatnya.' }, missions: [
      { id: 'unit-choice', title: 'Pilih Satuan', phase: 'AMATI', objective: 'Siswa dapat memilih satuan panjang dan luas yang sesuai dengan konteks.', type: 'choice', visual: 'LAPANGAN BOLA', prompt: 'Satuan yang tepat untuk luas lapangan sepak bola adalah ...', choices: ['meter persegi', 'liter', 'gram'], answer: 'meter persegi', explain: 'Luas diukur dengan satuan persegi seperti m².' },
      { id: 'time-interval', title: 'Hitung Durasi', phase: 'PECAHKAN', objective: 'Siswa dapat menghitung durasi kegiatan dari waktu mulai sampai selesai.', type: 'input', visual: '09.25 → 10.55', prompt: 'Durasi kegiatan adalah ... menit.', answer: '90', hint: 'Dari 09.25 ke 10.00 adalah 35 menit, lalu 55 menit.', explain: '35 + 55 = 90 menit.' }
    ] },
    { id: 'solid-shapes', code: '05', icon: '05', name: 'Lab Bangun Ruang', color: 'amber', question: 'Bagaimana jaring-jaring dan ukuran membentuk bangun ruang?', badge: 'PENJELAJAH BANGUN RUANG', challenge: { title: 'Rancang Kotak', prompt: 'Kenali bangun ruang dan hitung ukuran yang diperlukan.' }, missions: [
      { id: 'shape-classify', title: 'Klasifikasi Bangun', phase: 'AMATI → TEMUKAN', objective: 'Siswa dapat membandingkan sifat bangun datar berdasarkan sisi dan sudut.', type: 'choice', visual: '□  ◇  △', prompt: 'Bangun yang memiliki empat sisi sama panjang adalah ...', choices: ['Segitiga', 'Persegi', 'Lingkaran'], answer: 'Persegi', explain: 'Persegi memiliki empat sisi sama panjang dan empat sudut siku-siku.' },
      { id: 'perimeter-problem', title: 'Keliling Taman', phase: 'PECAHKAN → JELASKAN', objective: 'Siswa dapat menghitung keliling persegi panjang dan menjelaskan langkahnya.', type: 'input', visual: '12 m × 9 m', prompt: 'Keliling taman itu adalah ... m.', answer: '42', hint: 'Keliling = 2 × (p + l).', explain: '2 × (12 + 9) = 2 × 21 = 42 m.' }
    ] },
    { id: 'data', code: '06', icon: '06', name: 'Lab Data dan Diagram', color: 'teal', question: 'Bagaimana diagram membantu membaca dan menjelaskan data?', badge: 'DETEKTIF DATA', challenge: { title: 'Baca Diagram', prompt: 'Analisis diagram, bandingkan data, dan jelaskan kesimpulanmu.' }, missions: [
      { id: 'read-data', title: 'Baca Diagram Batang', phase: 'AMATI', objective: 'Siswa dapat membaca data statistik dan menarik kesimpulan sederhana.', type: 'choice', visual: 'Buah: Apel ███, Jeruk █████, Mangga ████', prompt: 'Buah yang paling banyak dipilih adalah ...', choices: ['Apel', 'Jeruk', 'Mangga'], answer: 'Jeruk', explain: 'Diagram jeruk paling panjang, berarti jumlahnya paling banyak.' },
      { id: 'data-logic', title: 'Analisis Data', phase: 'JELASKAN', objective: 'Siswa dapat membandingkan dua kelompok data dan menyusun alasan yang logis.', type: 'input', visual: '70, 75, 80, 85', prompt: 'Rata-rata dari data tersebut adalah ...', answer: '77.5', hint: 'Jumlah semua data dibagi 4.', explain: '70 + 75 + 80 + 85 = 310, lalu 310 ÷ 4 = 77,5.' }
    ] }
  ]
};