window.MATH_CONTENT = {
  title: 'Matematika Kelas 2 Semester 2', storageKey: 'grade2MathSemester2',
  tagline: 'Menguatkan operasi, pecahan sederhana, data, dan pemecahan masalah sehari-hari.',
  sourceNote: 'Pemetaan semester berbasis urutan pembelajaran dari CP/TP Kurikulum Merdeka Fase A; pembagian semester bukan pembagian resmi CP pemerintah.',
  chapters: [
    { id: 'bab-1', number: 1, world: 'DUNIA OPERASI', title: 'Operasi sampai 1.000', icon: '🔢', color: 'coral', goal: 'Menyelesaikan penjumlahan dan pengurangan bilangan sampai 1.000.', subs: [
      { title: 'Ratusan dan Puluhan', concept: 'Menggunakan nilai tempat untuk membaca bilangan.', activity: { type: 'pattern', mode: 'strategy', visual: '300 + 40 + 7', prompt: 'Cara menguraikan 347 yang tepat adalah ...', answer: '300 + 40 + 7', choices: ['300 + 40 + 7', '30 + 4 + 7', '300 + 7'], instruction: 'Perhatikan tempat ratusan, puluhan, dan satuan.', hints: ['3 ratusan bernilai 300.', '4 puluhan bernilai 40 dan 7 satuan bernilai 7.'], explanation: 'Benar. 347 terdiri dari 300, 40, dan 7.' } },
      { title: 'Tambah Ratusan', concept: 'Menjumlahkan bilangan dengan strategi nilai tempat.', activity: { type: 'sum', mode: 'input', visual: '240 + 130', prompt: '240 + 130 = ...', answer: 370, choices: [270, 370, 470], instruction: 'Gabungkan ratusan dan puluhan dengan tenang.', hints: ['240 + 100 = 340.', 'Tambahkan 30 lagi menjadi 370.'], explanation: 'Tepat. 240 + 130 = 370.' } },
      { title: 'Kurang Ratusan', concept: 'Mengurangkan bilangan sampai 1.000.', activity: { type: 'difference', mode: 'input', challenge: true, left: 560, right: 230, prompt: '560 - 230 = ...', answer: 330, choices: [230, 330, 430], instruction: 'Kurangkan ratusan dan puluhan sesuai nilai tempat.', hints: ['560 − 200 = 360.', 'Kurangi 30 lagi dari 360.'], explanation: 'Hebat. 560 − 230 = 330.' } }
    ] },
    { id: 'bab-2', number: 2, world: 'DUNIA PECAHAN', title: 'Pecahan Satu Kesatuan', icon: '🍕', color: 'sun', goal: 'Mengenali pecahan sederhana sebagai bagian dari satu benda utuh.', subs: [
      { title: 'Setengah', concept: 'Mengenali dua bagian sama besar sebagai 1/2.', activity: { type: 'shape', mode: 'strategy', visual: '◐  ◑', prompt: 'Cara menemukan setengah adalah ...', answer: 'Membagi utuh menjadi dua bagian sama besar', choices: ['Membagi utuh menjadi dua bagian sama besar', 'Membagi menjadi tiga bagian', 'Mengambil bagian paling kecil'], instruction: 'Bayangkan kue dibagi adil kepada dua anak.', hints: ['Setengah berarti dua bagian sama besar.', 'Masing-masing anak mendapat satu bagian.'], explanation: 'Benar. Setengah adalah satu dari dua bagian sama besar.' } },
      { title: 'Sepertiga', concept: 'Mengenali satu dari tiga bagian sama besar.', activity: { type: 'sequence', mode: 'sequence', visual: '◴  ◷  ◶', prompt: 'Susun nama pecahan dari bagian lebih sedikit ke lebih banyak.', answer: ['Sepertiga', 'Setengah', 'Utuh'], choices: ['Sepertiga', 'Setengah', 'Utuh'], instruction: 'Perhatikan bahwa satu bagian dari tiga adalah sepertiga.', hints: ['Sepertiga berarti satu dari tiga bagian.', 'Utuh berarti semua bagian digabung.'], explanation: 'Tepat. Sepertiga adalah satu dari tiga bagian sama besar.' } },
      { title: 'Bagian yang Sama', concept: 'Membedakan pembagian adil dan tidak adil.', activity: { type: 'compare', mode: 'strategy', challenge: true, visual: '🍪  |  🍪', prompt: 'Pecahan harus dibuat dari bagian yang ...', answer: 'Sama besar', choices: ['Sama besar', 'Berbeda', 'Paling kecil'], instruction: 'Periksa apakah setiap bagian mendapat ukuran yang sama.', hints: ['Pembagian adil berarti tidak ada bagian lebih besar.', 'Bandingkan ukuran setiap bagian.'], explanation: 'Benar. Pecahan menunjukkan bagian-bagian yang sama besar.' } }
    ] },
    { id: 'bab-3', number: 3, world: 'DUNIA DATA', title: 'Mengumpulkan dan Membaca Data', icon: '📊', color: 'leaf', goal: 'Membaca tabel dan diagram gambar sederhana.', subs: [
      { title: 'Tabel Pilihan', concept: 'Menghitung banyak data dalam tabel.', activity: { type: 'compare', mode: 'strategy', visual: 'Apel 4  •  Jeruk 6', prompt: 'Cara menentukan buah paling banyak adalah ...', answer: 'Membandingkan jumlahnya', choices: ['Membandingkan jumlahnya', 'Melihat nama buah', 'Menghitung hurufnya'], instruction: 'Bandingkan angka pada tabel.', hints: ['Apel berjumlah 4.', 'Jeruk berjumlah 6, lebih banyak daripada 4.'], explanation: 'Tepat. Jeruk paling banyak karena 6 lebih besar dari 4.' } },
      { title: 'Diagram Gambar', concept: 'Membandingkan panjang baris gambar.', activity: { type: 'sequence', mode: 'sequence', visual: 'Bola ●●●●  Buku ●●', prompt: 'Urutkan data dari yang lebih sedikit ke lebih banyak.', answer: ['Buku', 'Bola'], choices: ['Buku', 'Bola'], instruction: 'Mulai dari baris gambar yang paling pendek.', hints: ['Buku memiliki 2 gambar.', 'Bola memiliki 4 gambar.'], explanation: 'Benar. Buku lebih sedikit, lalu bola lebih banyak.' } },
      { title: 'Pertanyaan Data', concept: 'Menjawab pertanyaan berdasarkan data.', activity: { type: 'difference', mode: 'input', challenge: true, left: 9, right: 4, prompt: 'Ada 9 siswa suka apel dan 4 suka jeruk. Selisihnya ...', answer: 5, choices: [4, 5, 6], instruction: 'Kurangkan data yang lebih sedikit dari data yang lebih banyak.', hints: ['Gunakan 9 − 4.', 'Selisihnya adalah 5 siswa.'], explanation: 'Hebat. Selisih 9 dan 4 adalah 5 siswa.' } }
    ] },
    { id: 'bab-4', number: 4, world: 'DUNIA GEOMETRI', title: 'Bangun Ruang dan Posisi', icon: '🧊', color: 'sky', goal: 'Mengenali bentuk bangun ruang serta posisi benda.', subs: [
      { title: 'Kubus dan Balok', concept: 'Membedakan bangun ruang dari ciri dan bentuknya.', activity: { type: 'shape', mode: 'strategy', visual: '🎲  📦  ⚽', prompt: 'Cara mengenali benda yang menyerupai kubus adalah ...', answer: 'Memeriksa sisi-sisinya yang sama bentuk', choices: ['Memeriksa sisi-sisinya yang sama bentuk', 'Melihat warnanya saja', 'Mencari benda yang bisa menggelinding'], instruction: 'Bandingkan ciri dadu, kotak panjang, dan bola.', hints: ['Kubus memiliki sisi berbentuk persegi.', 'Dadu adalah contoh kubus.'], explanation: 'Benar. Dadu memiliki sisi persegi seperti kubus.' } },
      { title: 'Bergerak di Peta', concept: 'Mengikuti arah kanan, kiri, atas, dan bawah.', activity: { type: 'pattern', mode: 'sequence', visual: '⬆️  ➡️  ⬇️', prompt: 'Susun arah dari atas, berlawanan, lalu kanan.', answer: ['Atas', 'Bawah', 'Kanan'], choices: ['Atas', 'Bawah', 'Kanan'], instruction: 'Pilih arah sesuai urutan yang diminta.', hints: ['Arah berlawanan dengan atas adalah bawah.', 'Setelah itu pilih kanan.'], explanation: 'Tepat. Urutannya atas, bawah, lalu kanan.' } },
      { title: 'Jaring Bentuk', concept: 'Mengenali sisi datar pada bangun ruang.', activity: { type: 'shape', mode: 'strategy', challenge: true, visual: '□ □ □', prompt: 'Sisi kubus berbentuk ...', answer: 'Persegi', choices: ['Lingkaran', 'Persegi', 'Segitiga'], instruction: 'Lihat bentuk setiap sisi datar kubus.', hints: ['Sisi kubus seperti permukaan dadu.', 'Dadu memiliki permukaan berbentuk persegi.'], explanation: 'Benar. Setiap sisi kubus berbentuk persegi.' } }
    ] },
    { id: 'bab-5', number: 5, world: 'DUNIA STRATEGI', title: 'Soal Cerita dan Pola', icon: '🧩', color: 'violet', goal: 'Memilih operasi dan menjelaskan strategi untuk masalah sederhana.', subs: [
      { title: 'Pilih Operasi', concept: 'Menentukan apakah masalah perlu tambah atau kurang.', activity: { type: 'sum', mode: 'strategy', left: 24, right: 16, prompt: 'Ada 24 buku, datang 16 lagi. Operasinya ...', answer: 'Tambah', choices: ['Tambah', 'Kurang', 'Bagi'], instruction: 'Perhatikan apakah jumlah buku bertambah atau berkurang.', hints: ['Datang lagi berarti jumlahnya bertambah.', 'Gunakan penjumlahan.'], explanation: 'Tepat. Karena buku datang lagi, operasinya tambah.' } },
      { title: 'Lanjutkan Aturan', concept: 'Menemukan aturan pola bilangan.', activity: { type: 'pattern', mode: 'input', visual: '5 → 10 → 15 → ...', prompt: 'Bilangan berikutnya adalah ...', answer: 20, choices: [18, 20, 25], instruction: 'Cari selisih yang sama antarbilangan.', hints: ['Pola bertambah 5.', '15 ditambah 5 adalah 20.'], explanation: 'Benar. Polanya bertambah 5, jadi berikutnya 20.' } },
      { title: 'Langkah Masuk Akal', concept: 'Memeriksa apakah jawaban sesuai dengan cerita.', activity: { type: 'compare', mode: 'input', challenge: true, visual: '36 kelereng dibagi 4', prompt: '36 kelereng dibagi rata kepada 4 anak. Setiap anak mendapat ...', answer: 9, choices: [4, 9, 40], instruction: 'Gunakan pembagian sama rata.', hints: ['Cari bilangan yang jika dikali 4 menghasilkan 36.', '4 × 9 = 36.'], explanation: 'Hebat. Setiap anak mendapat 9 kelereng.' } }
    ] }
  ],
  finalChallenge: {
    title: 'Pesta Matematika Kiko',
    intro: 'Selesaikan lima misi singkat dengan menghitung, memilih bentuk, membaca waktu, dan menemukan pola.',
    tasks: [
      { prompt: 'Kiko memiliki 12 permen dan membaginya kepada 3 anak. Setiap anak mendapat ...', answer: 4, choices: [3, 4, 5], explanation: 'Benar. 12 dibagi 3 sama dengan 4.' },
      { prompt: 'Pecahan satu dari dua bagian sama besar disebut ...', answer: 'Setengah', choices: ['Setengah', 'Sepertiga', 'Utuh'], explanation: 'Tepat. Satu dari dua bagian sama besar adalah setengah.' },
      { prompt: 'Pola 3, 6, 9, ... dilanjutkan dengan ...', answer: 12, choices: [10, 12, 15], explanation: 'Hebat. Polanya bertambah 3.' },
      { prompt: 'Kegiatan pukul 07.00 sampai 09.00 berlangsung ... jam.', answer: 2, choices: [1, 2, 3], explanation: 'Benar. Dari 07.00 ke 09.00 adalah 2 jam.' },
      { prompt: 'Kiko membawa Rp10.000 dan membeli buku Rp5.000. Sisanya ... rupiah.', answer: 5000, choices: [4000, 5000, 6000], explanation: 'Tepat. Rp10.000 dikurangi Rp5.000 tersisa Rp5.000.' }
    ]
  }
};
