window.MATH_CONTENT = {
  title: 'Matematika Kelas 3 Semester 2', storageKey: 'grade3MathSemester2',
  tagline: 'Menerapkan pecahan, pola, pengukuran, dan data untuk memecahkan masalah.',
  sourceNote: 'Pemetaan semester berbasis urutan pembelajaran dari CP/TP Kurikulum Merdeka Fase B; pembagian semester bukan pembagian resmi CP pemerintah.',
  chapters: [
    { id: 'bab-1', number: 1, world: 'DUNIA PECAHAN', title: 'Pecahan dalam Cerita', icon: '🍉', color: 'coral', goal: 'Menggunakan pecahan untuk menjelaskan bagian dan hasil pengukuran.', subs: [
      { title: 'Pecahan dari Benda', concept: 'Menentukan pecahan berdasarkan bagian yang diarsir.', activity: { type: 'shape', mode: 'strategy', visual: '◕  ◔', prompt: 'Cara mengenali 1/4 dari sebuah benda adalah ...', answer: 'Satu dari empat bagian sama besar', choices: ['Satu dari empat bagian sama besar', 'Empat bagian tidak sama', 'Satu bagian dari dua'], instruction: 'Perhatikan banyak bagian yang sama besar.', hints: ['Penyebut menunjukkan jumlah seluruh bagian.', 'Pembilang 1 berarti memilih satu bagian.'], explanation: 'Benar. 1/4 berarti satu dari empat bagian yang sama besar.' } },
      { title: 'Pecahan di Garis Bilangan', concept: 'Menempatkan pecahan sederhana di antara 0 dan 1.', activity: { type: 'pattern', mode: 'sequence', visual: '0 ─ 1/2 ─ 1', prompt: 'Susun titik dari yang paling kecil ke paling besar.', answer: ['0', '1/2', '1'], choices: ['0', '1/2', '1'], instruction: 'Mulai dari 0, lalu pecahan di tengah, kemudian 1.', hints: ['0 lebih kecil daripada semua pecahan positif.', '1/2 berada di antara 0 dan 1.'], explanation: 'Tepat. Garis bilangan bergerak dari 0 ke 1.' } },
      { title: 'Masalah Pecahan', concept: 'Menjelaskan bagian yang digunakan atau tersisa.', activity: { type: 'difference', mode: 'input', challenge: true, left: 8, right: 3, visual: '8 potong − 3 potong', prompt: 'Dari 8 potong, 3 dimakan. Tersisa ...', answer: 5, choices: [4, 5, 6], instruction: 'Gunakan pengurangan untuk mencari bagian yang tersisa.', hints: ['Tersisa berarti jumlah awal dikurangi yang dimakan.', 'Hitung 8 − 3.'], explanation: 'Hebat. 8 − 3 = 5 potong tersisa.' } }
    ] },
    { id: 'bab-2', number: 2, world: 'DUNIA POLA', title: 'Pola dan Kalimat Matematika', icon: '🔁', color: 'sun', goal: 'Menemukan aturan pola dan menggunakan simbol pada kalimat matematika.', subs: [
      { title: 'Pola Bilangan', concept: 'Menemukan perubahan tetap pada pola.', activity: { type: 'pattern', mode: 'input', visual: '4 → 8 → 12 → ...', prompt: 'Bilangan berikutnya adalah ...', answer: 16, choices: [14, 16, 20], instruction: 'Cari perubahan yang sama dari satu bilangan ke bilangan berikutnya.', hints: ['8 − 4 = 4 dan 12 − 8 = 4.', 'Tambahkan 4 pada 12.'], explanation: 'Benar. Polanya bertambah 4, jadi berikutnya 16.' } },
      { title: 'Bilangan yang Hilang', concept: 'Menentukan nilai yang membuat kalimat benar.', activity: { type: 'difference', mode: 'input', visual: '□ + 17 = 45', prompt: 'Bilangan yang hilang adalah ...', answer: 28, choices: [18, 28, 32], instruction: 'Cari bilangan yang jika ditambah 17 menghasilkan 45.', hints: ['Gunakan kebalikan penjumlahan: 45 − 17.', '45 − 17 = 28.'], explanation: 'Tepat. 28 + 17 = 45.' } },
      { title: 'Aturan Mesin', concept: 'Mengikuti aturan input dan output sederhana.', activity: { type: 'pattern', mode: 'strategy', challenge: true, visual: '2 → 5, 3 → 6, 4 → ...', prompt: 'Strategi untuk menemukan output adalah ...', answer: 'Menemukan aturan tambah 3', choices: ['Menemukan aturan tambah 3', 'Mengalikan input dengan 3', 'Mengurangi input dengan 3'], instruction: 'Bandingkan setiap input dengan outputnya.', hints: ['5 − 2 = 3 dan 6 − 3 = 3.', 'Aturannya adalah tambah 3.'], explanation: 'Hebat. Mesin menambahkan 3 pada setiap input.' } }
    ] },
    { id: 'bab-3', number: 3, world: 'DUNIA PENGUKURAN', title: 'Waktu dan Panjang', icon: '⏱️', color: 'leaf', goal: 'Menggunakan satuan dan hubungan waktu dalam situasi nyata.', subs: [
      { title: 'Durasi Kegiatan', concept: 'Menentukan lama kegiatan dari waktu mulai dan selesai.', activity: { type: 'difference', mode: 'input', visual: '08.00 → 10.00', prompt: 'Lama kegiatan adalah ... jam.', answer: 2, choices: [1, 2, 3], instruction: 'Hitung lompatan waktu dari pukul 08.00 ke 10.00.', hints: ['Dari 08.00 ke 09.00 satu jam.', 'Dari 09.00 ke 10.00 satu jam lagi.'], explanation: 'Benar. Durasi kegiatan adalah 2 jam.' } },
      { title: 'Konversi Panjang', concept: 'Menghubungkan meter dan sentimeter.', activity: { type: 'pattern', mode: 'input', visual: '1 m = ... cm', prompt: '1 meter sama dengan ... sentimeter.', answer: 100, choices: [10, 100, 1.000], instruction: 'Ingat hubungan satu meter dengan sentimeter.', hints: ['Satu meter terdiri dari 100 sentimeter.', 'Jawabannya 100 cm.'], explanation: 'Tepat. 1 m = 100 cm.' } },
      { title: 'Perkirakan Ukuran', concept: 'Memilih perkiraan ukuran yang wajar.', activity: { type: 'compare', mode: 'strategy', challenge: true, visual: 'papan tulis  •  2 m / 20 cm', prompt: 'Alasan memilih ukuran papan tulis yang masuk akal adalah ...', answer: 'Papan tulis lebih panjang dari penggaris', choices: ['Papan tulis lebih panjang dari penggaris', 'Papan tulis hanya sepanjang jari', 'Semua ukuran sama'], instruction: 'Gunakan benda yang pernah kamu lihat sebagai pembanding.', hints: ['Papan tulis digunakan seluruh kelas.', 'Ukuran 2 m lebih masuk akal daripada 20 cm.'], explanation: 'Benar. Papan tulis lebih masuk akal jika panjangnya sekitar 2 m.' } }
    ] },
    { id: 'bab-4', number: 4, world: 'DUNIA GEOMETRI', title: 'Sudut dan Simetri', icon: '📐', color: 'sky', goal: 'Mengenali sudut dan simetri pada bangun serta benda sekitar.', subs: [
      { title: 'Sudut Siku-siku', concept: 'Mengenali sudut seperti pojok buku.', activity: { type: 'shape', mode: 'strategy', visual: '∟  ∠  ○', prompt: 'Cara mengenali sudut siku-siku adalah ...', answer: 'Mencocokkannya dengan pojok buku', choices: ['Mencocokkannya dengan pojok buku', 'Menghitung warnanya', 'Mengukur panjang sisi saja'], instruction: 'Bandingkan sudut dengan pojok buku.', hints: ['Pojok buku membentuk sudut siku-siku.', 'Cari bentuk sudut seperti huruf L.'], explanation: 'Tepat. Sudut siku-siku tampak seperti pojok buku.' } },
      { title: 'Garis Simetri', concept: 'Menemukan garis yang membagi bentuk menjadi dua bagian sama.', activity: { type: 'shape', mode: 'strategy', visual: '♥  |  ♥', prompt: 'Garis simetri membuat bentuk menjadi ...', answer: 'Dua bagian yang sama', choices: ['Dua bagian yang sama', 'Dua bagian berbeda', 'Satu bagian saja'], instruction: 'Bayangkan bentuk dilipat pada garis tersebut.', hints: ['Kedua sisi harus saling menutupi.', 'Garis itu membagi bentuk menjadi dua bagian sama.'], explanation: 'Benar. Garis simetri membagi bentuk menjadi dua bagian yang sama.' } },
      { title: 'Rancang Bangun', concept: 'Memilih bangun berdasarkan ciri yang dibutuhkan.', activity: { type: 'compare', mode: 'sequence', challenge: true, visual: '3 sisi  •  4 sisi', prompt: 'Susun bangun dari yang memiliki 3 sisi ke 4 sisi.', answer: ['Segitiga', 'Persegi'], choices: ['Segitiga', 'Persegi'], instruction: 'Mulai dari bangun dengan sisi lebih sedikit.', hints: ['Segitiga memiliki 3 sisi.', 'Persegi memiliki 4 sisi.'], explanation: 'Hebat. Segitiga memiliki 3 sisi, lalu persegi memiliki 4 sisi.' } }
    ] },
    { id: 'bab-5', number: 5, world: 'DUNIA PEMECAH MASALAH', title: 'Misi Matematika', icon: '🧩', color: 'violet', goal: 'Memilih strategi, menalar, dan memeriksa jawaban dari masalah multi-langkah.', subs: [
      { title: 'Belanja Cermat', concept: 'Menggabungkan penjumlahan dan pengurangan dalam cerita.', activity: { type: 'difference', mode: 'input', left: 50, right: 32, visual: 'Rp50.000 − Rp32.000', prompt: 'Kembalian dari Rp50.000 untuk belanja Rp32.000 adalah ... ribu rupiah.', answer: 18, choices: [8, 18, 28], instruction: 'Kurangi harga belanja dari uang yang dibawa.', hints: ['Gunakan 50 − 32.', '50 − 32 = 18 ribu rupiah.'], explanation: 'Benar. Kembaliannya Rp18.000.' } },
      { title: 'Rute Terpendek', concept: 'Membandingkan jarak dan memilih rute masuk akal.', activity: { type: 'compare', mode: 'strategy', visual: 'Rute A 450 m  •  Rute B 300 m', prompt: 'Strategi untuk memilih rute terpendek adalah ...', answer: 'Membandingkan jaraknya', choices: ['Membandingkan jaraknya', 'Memilih nama paling pendek', 'Menjumlahkan nama rute'], instruction: 'Bandingkan angka jarak kedua rute.', hints: ['450 lebih besar daripada 300.', 'Jarak lebih kecil berarti rute lebih pendek.'], explanation: 'Tepat. Rute B lebih pendek karena 300 m lebih kecil.' } },
      { title: 'Periksa Jawaban', concept: 'Menggunakan perkiraan untuk memeriksa hasil.', activity: { type: 'sum', mode: 'input', challenge: true, left: 198, right: 201, visual: '198 + 201 ≈ ...', prompt: 'Perkiraan terdekat adalah ...', answer: 400, choices: [300, 400, 500], instruction: 'Bulatkan kedua bilangan ke ratusan terdekat.', hints: ['198 mendekati 200 dan 201 mendekati 200.', '200 + 200 = 400.'], explanation: 'Hebat. Perkiraan 198 + 201 adalah 400.' } }
    ] }
  ],
  finalChallenge: {
    title: 'Petualangan Akhir Semester',
    intro: 'Bantu Kiko menyelesaikan lima misi matematika dengan strategi terbaik.',
    tasks: [
      { prompt: 'Setengah dari 12 kue adalah ...', answer: 6, choices: [4, 6, 8], explanation: 'Benar. Setengah dari 12 berarti 12 dibagi 2, hasilnya 6.' },
      { prompt: 'Pola 6, 12, 18, ... dilanjutkan dengan ...', answer: 24, choices: [20, 24, 30], explanation: 'Tepat. Polanya bertambah 6.' },
      { prompt: 'Kegiatan mulai pukul 09.00 dan selesai 11.00. Durasi kegiatan ... jam.', answer: 2, choices: [1, 2, 3], explanation: 'Benar. Dari pukul 09.00 ke 11.00 adalah 2 jam.' },
      { prompt: 'Bangun dengan 4 sisi sama panjang adalah ...', answer: 'Persegi', choices: ['Segitiga', 'Persegi', 'Lingkaran'], explanation: 'Tepat. Persegi memiliki empat sisi sama panjang.' },
      { prompt: 'Uang Rp20.000 dikurangi Rp8.000 tersisa ... rupiah.', answer: 12000, choices: [8000, 12000, 18000], explanation: 'Hebat. Rp20.000 - Rp8.000 = Rp12.000.' }
    ]
  }
};
