window.MATH_LAB = {
  storageKey: 'grade6MathSemester2',
  title: 'Math Lab',
  labs: [
    { id: 'review-bilangan', code: '01', icon: '01', name: 'Lab Penguatan Bilangan', color: 'amber', question: 'Mampukah kamu menguji jawaban dengan logika?', badge: 'PENGUAT BILANGAN', challenge: { title: 'Review Cepat', prompt: 'Kuatkan operasi, bandingkan hasil, dan pastikan jawaban masuk akal.' }, missions: [
      { id: 'estimate-check', title: 'Perkirakan dan Uji', phase: 'REVIEW', objective: 'Siswa dapat memperkirakan hasil operasi dan memeriksa kewajarannya.', type: 'choice', visual: '498 + 197', prompt: 'Hasil yang paling masuk akal adalah ...', choices: ['600', '700', '800'], answer: '700', explain: '498 + 197 ≈ 500 + 200 = 700.' },
      { id: 'number-strategy', title: 'Pilih Strategi', phase: 'APPLY', objective: 'Siswa dapat memilih strategi hitung yang paling efisien untuk bilangan besar.', type: 'input', visual: '25 × 48', prompt: 'Hasilnya adalah ...', answer: '1200', hint: '25 × 48 = 25 × 50 - 25 × 2.', explain: '25 × 50 = 1250, lalu kurangi 50 menjadi 1200.' }
    ] },
    { id: 'fraction-decimal', code: '02', icon: '02', name: 'Lab Pecahan dan Desimal', color: 'coral', question: 'Bagaimana kita menilai solusi yang paling tepat?', badge: 'PENERAP PECAHAN', challenge: { title: 'Pecahan dalam Kehidupan', prompt: 'Terapkan pecahan dan desimal pada situasi nyata lalu presentasikan alasanmu.' }, missions: [
      { id: 'fraction-apply', title: 'Selesaikan Masalah', phase: 'APPLY', objective: 'Siswa dapat menerapkan pecahan dalam situasi nyata dan menjelaskan langkahnya.', type: 'choice', visual: '3/4 dari 40', prompt: 'Hasilnya adalah ...', choices: ['20', '30', '10'], answer: '30', explain: '40 ÷ 4 = 10, lalu 10 × 3 = 30.' },
      { id: 'decimal-verify', title: 'Verifikasi Desimal', phase: 'EXPLAIN', objective: 'Siswa dapat membandingkan hasil desimal dan membuktikan jawabannya benar.', type: 'input', visual: '0,8 + 0,35', prompt: 'Hasilnya adalah ...', answer: '1,15', hint: '0,80 + 0,35 = 1,15.', explain: '8 persepuluh ditambah 35 per seratus sama dengan 115 per seratus.' }
    ] },
    { id: 'ratio-comparison', code: '03', icon: '03', name: 'Lab Rasio dan Perbandingan', color: 'blue', question: 'Bagaimana perbandingan membantu memilih solusi yang tepat?', badge: 'PENEMU STRATEGI', challenge: { title: 'Bandingkan dengan Rasio', prompt: 'Gunakan rasio untuk membandingkan besaran dan menjelaskan keputusanmu.' }, missions: [
      { id: 'ratio-review', title: 'Sederhanakan Rasio', phase: 'APPLY', objective: 'Siswa dapat menyederhanakan rasio dan menjelaskan hubungan antarbesaran.', type: 'choice', visual: '12 : 18', prompt: 'Bentuk paling sederhana dari 12 : 18 adalah ...', choices: ['2 : 3', '3 : 4', '4 : 5'], answer: '2 : 3', explain: '12 dan 18 sama-sama dibagi 6, sehingga menjadi 2 : 3.' },
      { id: 'ratio-context', title: 'Rasio dalam Konteks', phase: 'EXPLAIN', objective: 'Siswa dapat menerapkan rasio untuk menyelesaikan masalah kontekstual.', type: 'input', visual: '2 : 5 dari 35', prompt: 'Bagian yang sesuai dengan 2 dari setiap 5 bagian adalah ...', answer: '14', hint: '35 dibagi 5, lalu dikalikan 2.', explain: '35 ÷ 5 × 2 = 14.' }
    ] },
    { id: 'measurement-geometry', code: '04', icon: '04', name: 'Lab Geometri dan Pengukuran', color: 'green', question: 'Kapan lantai, ruang, dan bentuk harus dihitung bersama?', badge: 'GEOMETRI AKTIF', challenge: { title: 'Pilih Solusi Terbaik', prompt: 'Hitung ukuran, pilih strategimu, dan jelaskan alasan dari pilihan itu.' }, missions: [
      { id: 'perimeter-challenge', title: 'Keliling Ruang', phase: 'SOLVE', objective: 'Siswa dapat menghitung keliling suatu ruang dan memilih strategi yang paling sederhana.', type: 'input', visual: '12 m × 9 m', prompt: 'Keliling ruang tersebut adalah ... m.', answer: '42', hint: 'Keliling = 2 × (12 + 9).', explain: '2 × 21 = 42 m.' },
      { id: 'volume-apply', title: 'Volume Wadah', phase: 'APPLY → EXPLAIN', objective: 'Siswa dapat menghitung volume wadah dan menilai apakah hasilnya masuk akal.', type: 'choice', visual: '6 cm × 4 cm × 5 cm', prompt: 'Volume wadah itu adalah ... cm³.', choices: ['120', '90', '60'], answer: '120', explain: '6 × 4 × 5 = 120 cm³.' }
    ] },
    { id: 'data-probability', code: '05', icon: '05', name: 'Lab Data dan Peluang', color: 'teal', question: 'Bagaimana data dan peluang membantu keputusan?', badge: 'PELAJAR DATA', challenge: { title: 'Tafsirkan dan Pilih', prompt: 'Baca data, pilih kesimpulan, dan buat keputusan yang paling logis.' }, missions: [
      { id: 'data-interpret', title: 'Interpretasi Data', phase: 'REVIEW', objective: 'Siswa dapat membaca diagram data dan menyimpulkan pola yang muncul.', type: 'choice', visual: 'Nilai: 62, 74, 80, 74, 90', prompt: 'Median data tersebut adalah ...', choices: ['74', '80', '90'], answer: '74', explain: 'Data terurut: 62, 74, 74, 80, 90; angka tengahnya 74.' },
      { id: 'probability-event', title: 'Peluang Sederhana', phase: 'FINAL CHALLENGE', objective: 'Siswa dapat menghitung peluang kejadian sederhana dan menjelaskan hasilnya.', type: 'input', visual: '5 bola: 2 kuning, 3 hijau', prompt: 'Peluang mengambil bola kuning adalah ...', answer: '2/5', hint: 'Jumlah kemungkinan total = 5.', explain: '2 dari 5 bola berwarna kuning, jadi 2/5.' }
    ] },
    { id: 'final-challenge', code: '06', icon: '06', name: 'Lab Problem Solving Terpadu', color: 'violet', question: 'Apakah kamu siap menyelesaikan tantangan terintegrasi?', badge: '🏆 MISI AKHIR', challenge: { title: '🏆 Misi Akhir Matematika', prompt: 'Gabungkan bilangan, pecahan, rasio, geometri, dan data untuk memahami masalah, memilih strategi, dan menjelaskan jawabanmu.' }, missions: [
      { id: 'final-problem', title: 'Misi Akhir Matematika', phase: 'FINAL CHALLENGE', objective: 'Siswa dapat memecahkan masalah gabungan yang melibatkan beberapa konsep sekaligus.', type: 'input', visual: 'Kebun: 8 m × 6 m, 3/4 ditanami', prompt: 'Luas area yang ditanami adalah ... m².', answer: '36', hint: 'Luas kebun = 8 × 6 = 48, lalu 3/4 dari 48 = 36.', explain: '48 × 3/4 = 36 m².' },
      { id: 'final-explain', title: 'Jelaskan Alasanmu', phase: 'EXPLAIN', objective: 'Siswa dapat menjelaskan pilihan strategi, langkah, dan hasil akhir dengan jelas.', type: 'choice', visual: '50 siswa, 2/5 mengikuti lomba', prompt: 'Banyak siswa yang mengikuti lomba adalah ...', choices: ['10', '20', '25'], answer: '20', explain: '2/5 dari 50 = 20.' }
    ] }
  ]
};