window.MATH_LAB = {
  storageKey: 'grade5MathSemester1',
  title: 'Math Lab',
  labs: [
    { id: 'number', code: '01', icon: '01', name: 'Lab Bilangan', color: 'amber', question: 'Bagaimana angka besar membantu kita menguji strategi?', badge: 'PENJELAJAH BILANGAN', challenge: { title: 'Pilih Nilai terbaik', prompt: 'Analisis nilai tempat, urutan, dan pola agar keputusanmu efisien.' }, missions: [
      { id: 'digit-value', title: 'Nilai Digit', phase: 'AMATI', objective: 'Siswa dapat menentukan nilai digit dalam bilangan besar dan membandingkannya.', type: 'choice', visual: '65.482.930', prompt: 'Digit 8 pada bilangan 65.482.930 bernilai ...', choices: ['8 juta', '80 ribu', '8 ribu'], answer: '80 ribu', explain: 'Digit 8 berada di posisi puluh ribuan, jadi nilainya 80.000.' },
      { id: 'median-order', title: 'Urutkan dan Pilih', phase: 'ANALISIS → PILIH STRATEGI', objective: 'Siswa dapat mengurutkan bilangan dan memilih strategi yang paling efisien.', type: 'input', visual: '2.450; 2.405; 2.540; 2.495', prompt: 'Bilangan terbesar dari data tersebut adalah ...', answer: '2540', hint: 'Bandingkan digit ribuan, ratusan, dan puluhan.', explain: '2.540 lebih besar dari 2.495 dan 2.450.' }
    ] },
    { id: 'operations', code: '02', icon: '02', name: 'Lab Operasi Hitung', color: 'blue', question: 'Bisakah kamu memilih cara hitung yang paling efektif?', badge: 'PENEMU STRATEGI', challenge: { title: 'Cek dan Bandingkan', prompt: 'Pilih strategi, bandingkan hasil, dan jelaskan alasanmu.' }, missions: [
      { id: 'efficient-multiplication', title: 'Perkalian Efisien', phase: 'PILIH STRATEGI', objective: 'Siswa dapat memilih strategi yang paling efektif untuk mengalikan bilangan besar.', type: 'choice', visual: '24 × 25', prompt: 'Strategi paling efisien adalah ...', choices: ['24 × 100 ÷ 4', '24 + 25', '24 × 2 + 5'], answer: '24 × 100 ÷ 4', explain: '25 = 100 ÷ 4, sehingga perkalian menjadi lebih sederhana.' },
      { id: 'solve-two-step', title: 'Masalah Dua Langkah', phase: 'PECAHKAN', objective: 'Siswa dapat memecahkan soal dua langkah dengan operasi yang tepat.', type: 'input', visual: '12 × 8 + 36', prompt: 'Hasilnya adalah ...', answer: '132', hint: 'Lakukan perkalian dahulu, lalu tambahkan.', explain: '12 × 8 = 96, lalu 96 + 36 = 132.' }
    ] },
    { id: 'fraction', code: '03', icon: '03', name: 'Lab Pecahan', color: 'coral', question: 'Apa yang membuat dua pecahan sama nilainya?', badge: 'PENJELAJAH PECAHAN', challenge: { title: 'Eksplorasi Pecahan', prompt: 'Bandingkan pecahan, cari bentuk senilai, dan jelaskan alasanmu.' }, missions: [
      { id: 'fraction-equivalent', title: 'Bentuk Senilai', phase: 'AMATI → ANALISIS', objective: 'Siswa dapat menemukan pecahan senilai dan menjelaskan hubungan antar pembilang dan penyebut.', type: 'choice', visual: '3/4 = ?', prompt: 'Pecahan yang senilai dengan 3/4 adalah ...', choices: ['6/8', '4/5', '2/3'], answer: '6/8', explain: 'Kalikan pembilang dan penyebut dengan 2 menghasilkan 6/8.' },
      { id: 'fraction-order', title: 'Urutkan Pecahan', phase: 'JELASKAN', objective: 'Siswa dapat menyusun pecahan dari yang terkecil ke terbesar dengan bukti yang jelas.', type: 'sequence', visual: '0 ───────── 1', prompt: 'Urutkan dari terkecil ke terbesar.', choices: ['1/2', '2/3', '3/5'], answer: ['1/2', '3/5', '2/3'], explain: '1/2 = 0,5; 3/5 = 0,6; 2/3 ≈ 0,67.' }
    ] },
    { id: 'decimal-percent', code: '04', icon: '04', name: 'Lab Desimal dan Persen', color: 'green', question: 'Bagaimana desimal dan persen mewakili bagian dari keseluruhan?', badge: 'PENJELAJAH NILAI', challenge: { title: 'Ubah dan Bandingkan', prompt: 'Hubungkan desimal, pecahan, dan persen dalam konteks nyata.' }, missions: [
      { id: 'unit-match', title: 'Cocokkan Satuan', phase: 'AMATI', objective: 'Siswa dapat memilih satuan yang tepat untuk luas, panjang, dan isi.', type: 'choice', visual: 'KOLAM RENANG', prompt: 'Satuan yang paling tepat untuk volume kolam renang adalah ...', choices: ['meter kubik', 'meter', 'kilogram'], answer: 'meter kubik', explain: 'Volume diukur dengan satuan kubik seperti m³.' },
      { id: 'volume-solve', title: 'Hitung Volume', phase: 'PECAHKAN → JELASKAN', objective: 'Siswa dapat menghitung volume bangun ruang sederhana dalam konteks nyata.', type: 'input', visual: '5 cm × 4 cm × 3 cm', prompt: 'Volume balok tersebut adalah ... cm³.', answer: '60', hint: 'Volume = panjang × lebar × tinggi.', explain: '5 × 4 × 3 = 60 cm³.' }
    ] },
    { id: 'geometry-measurement', code: '05', icon: '05', name: 'Lab Geometri dan Pengukuran', color: 'violet', question: 'Bagaimana sifat bentuk dan satuan membantu kita memecahkan masalah?', badge: 'DETEKTIF GEOMETRI', challenge: { title: 'Rancang Lantai', prompt: 'Pilih bentuk, hitung ukuran, lalu bandingkan strategi.' }, missions: [
      { id: 'angle-compare', title: 'Bandingkan Sudut', phase: 'ANALISIS', objective: 'Siswa dapat membandingkan besar sudut dan mengidentifikasi jenis sudut.', type: 'choice', visual: '∠A = 90° ; ∠B = 47°', prompt: 'Sudut yang lebih besar adalah ...', choices: ['∠A', '∠B', 'Sama'], answer: '∠A', explain: '90° lebih besar daripada 47°.' },
      { id: 'area-and-perimeter', title: 'Luas dan Keliling', phase: 'PILIH STRATEGI → PECAHKAN', objective: 'Siswa dapat memilih strategi yang tepat untuk menghitung luas atau keliling suatu bangun.', type: 'input', visual: '12 m × 7 m', prompt: 'Luas persegi panjang tersebut adalah ... m².', answer: '84', hint: 'Luas = panjang × lebar.', explain: '12 × 7 = 84 m².' }
    ] },
    { id: 'data', code: '06', icon: '06', name: 'Lab Data', color: 'teal', question: 'Apa yang dapat kita simpulkan dari data yang berubah?', badge: 'DETEKTIF DATA', challenge: { title: 'Membaca Tren', prompt: 'Tafsirkan tabel, pilih kesimpulan yang paling masuk akal, lalu jelaskan.' }, missions: [
      { id: 'table-interpret', title: 'Interpretasi Tabel', phase: 'AMATI', objective: 'Siswa dapat membaca tabel dan menarik kesimpulan yang tepat.', type: 'choice', visual: 'Siswa: 32, 40, 28, 37', prompt: 'Kenaikan terbesar terjadi pada ...', choices: ['32 ke 40', '40 ke 28', '28 ke 37'], answer: '32 ke 40', explain: 'Selisih 8 adalah kenaikan terbesar di antara semua pasangan.' },
      { id: 'mean-data', title: 'Rata-rata Data', phase: 'VERIFIKASI', objective: 'Siswa dapat menghitung rata-rata dan memeriksa apakah hasilnya masuk akal.', type: 'input', visual: '12, 14, 16, 18', prompt: 'Rata-ratanya adalah ...', answer: '15', hint: 'Jumlah semua data = 60, dibagi 4.', explain: '12 + 14 + 16 + 18 = 60; 60 ÷ 4 = 15.' }
    ] }
  ]
};