window.MATH_LAB = {
  storageKey: 'grade4MathSemester1',
  title: 'Math Lab',
  labs: [
    { id: 'number', code: '01', icon: '01', name: 'Lab Bilangan', color: 'amber', question: 'Bagaimana angka besar tersusun?', badge: 'PENJELAJAH BILANGAN', challenge: { title: 'Bongkar Bilangan', prompt: 'Baca, uraikan, dan perkirakan bilangan dalam konteks nyata.' }, missions: [
      { id: 'place-value', title: 'Bongkar Bilangan', phase: 'AMATI', objective: 'Siswa dapat menentukan nilai tempat suatu digit.', type: 'choice', visual: '4 | 582 | 300', prompt: 'Nilai angka 5 pada 4.582.300 adalah ...', choices: ['5 ribu', '500 ribu', '50 ribu'], answer: '500 ribu', explain: 'Angka 5 berada pada tempat ratusan ribu.' },
      { id: 'estimate', title: 'Uji Estimasi', phase: 'PERKIRAKAN → UJI', objective: 'Siswa dapat menggunakan strategi kompensasi untuk berhitung efisien.', type: 'input', visual: '398 + 197', prompt: 'Gunakan strategi 398 + 200 - 3. Hasilnya ...', answer: '595', hint: '398 + 200 = 598, lalu kurangi 3.', explain: 'Strategi kompensasi menghasilkan 595.' }
    ] },
    { id: 'operations', code: '02', icon: '02', name: 'Lab Operasi Hitung', color: 'blue', question: 'Bisakah kamu menemukan strategi tercepat?', badge: 'PENEMU STRATEGI', challenge: { title: 'Perbaiki Solusi', prompt: 'Periksa solusi, temukan kesalahan, lalu jelaskan perbaikannya.' }, missions: [
      { id: 'strategy', title: 'Pilih Strategi', phase: 'JELAJAHI', objective: 'Siswa dapat memilih strategi perkalian yang efisien.', type: 'choice', visual: '48 × 25', prompt: 'Strategi yang paling membantu adalah ...', choices: ['48 × 100 ÷ 4', '48 + 25', '48 - 25'], answer: '48 × 100 ÷ 4', explain: '25 adalah seperempat dari 100, jadi strateginya efisien.' },
      { id: 'error', title: 'Deteksi Kesalahan', phase: 'PERIKSA → PERBAIKI', objective: 'Siswa dapat memeriksa kewajaran hasil dan memperbaiki kesalahan.', type: 'error', visual: '245 + 178 = 313', prompt: 'Apakah perhitungan Andi benar?', choices: ['Benar', 'Salah'], answer: 'Salah', hint: 'Perkirakan: 245 + 178 mendekati 400.', explain: 'Salah. Hasil yang benar adalah 423.' }
    ] },
    { id: 'fraction', code: '03', icon: '03', name: 'Lab Pecahan', color: 'coral', question: 'Apa hubungan bagian dan keseluruhan?', badge: 'PENJELAJAH PECAHAN', challenge: { title: 'Bangun Keseluruhan', prompt: 'Gunakan batang pecahan dan garis bilangan untuk membandingkan bagian.' }, missions: [
      { id: 'equivalent', title: 'Temukan Pecahan Senilai', phase: 'TEMUKAN', objective: 'Siswa dapat mengenali pecahan senilai melalui representasi visual.', type: 'choice', visual: '▰▰□□ = ?', prompt: 'Pecahan yang senilai dengan 1/2 adalah ...', choices: ['2/4', '1/4', '3/4'], answer: '2/4', explain: 'Dua dari empat bagian sama dengan setengah.' },
      { id: 'number-line', title: 'Batang Pecahan', phase: 'TERAPKAN', objective: 'Siswa dapat mengurutkan pecahan menggunakan garis bilangan.', type: 'sequence', visual: '0 ───── 1', prompt: 'Urutkan dari terkecil ke terbesar.', choices: ['1/4', '1/2', '3/4'], answer: ['1/4', '1/2', '3/4'], explain: 'Pada garis bilangan, semakin ke kanan nilainya semakin besar.' }
    ] },
    { id: 'geometry', code: '04', icon: '04', name: 'Lab Geometri', color: 'violet', question: 'Apakah bentuk berubah saat diputar?', badge: 'DETEKTIF GEOMETRI', challenge: { title: 'Rancang Taman Bermain', prompt: 'Pilih bentuk, bandingkan sifatnya, lalu hitung kelilingnya.' }, missions: [
      { id: 'classify', title: 'Klasifikasi Bentuk', phase: 'AMATI → KELOMPOKKAN', objective: 'Siswa dapat mengklasifikasikan bangun berdasarkan jumlah sisinya.', type: 'choice', visual: '◇  ▭  ○', prompt: 'Bangun dengan empat sisi adalah ...', choices: ['Lingkaran', 'Segiempat', 'Segitiga'], answer: 'Segiempat', explain: 'Segiempat memiliki empat sisi, meskipun orientasinya berbeda.' },
      { id: 'perimeter', title: 'Rancang Taman', phase: 'PECAHKAN', objective: 'Siswa dapat menghitung keliling persegi panjang dalam konteks desain.', type: 'input', visual: '8 m × 5 m', prompt: 'Keliling taman persegi panjang ini adalah ... m.', answer: '26', hint: 'Jumlahkan 8 + 5 + 8 + 5.', explain: 'Keliling = 8 + 5 + 8 + 5 = 26 m.' }
    ] },
    { id: 'measurement', code: '05', icon: '05', name: 'Lab Pengukuran', color: 'green', question: 'Seberapa dekat perkiraanmu?', badge: 'PENJELAJAH UKURAN', challenge: { title: 'Ukur Ruangan', prompt: 'Perkirakan, ukur, lalu bandingkan hasil pengukuranmu.' }, missions: [
      { id: 'unit', title: 'Pilih Satuan', phase: 'AMATI', objective: 'Siswa dapat memilih satuan yang sesuai untuk mengukur panjang.', type: 'choice', visual: 'MEJA KELAS', prompt: 'Satuan yang paling tepat untuk panjang meja adalah ...', choices: ['sentimeter', 'kilometer', 'gram'], answer: 'sentimeter', explain: 'Meja dapat diukur dengan sentimeter atau meter, bukan kilometer atau gram.' },
      { id: 'duration', title: 'Baca Durasi', phase: 'UJI', objective: 'Siswa dapat menentukan durasi dengan membaca waktu mulai dan selesai.', type: 'input', visual: '08.15 → 09.00', prompt: 'Durasi kegiatan adalah ... menit.', answer: '45', hint: 'Dari 08.15 ke 09.00.', explain: '15 menit menuju 08.30, lalu 30 menit menuju 09.00. Total 45 menit.' }
    ] },
    { id: 'data', code: '06', icon: '06', name: 'Lab Data', color: 'teal', question: 'Apa yang dapat kamu simpulkan dari data?', badge: 'DETEKTIF DATA', challenge: { title: 'Misi Matematika Besar', prompt: 'Gabungkan ukuran, pecahan, luas, dan data untuk merancang taman mini.' }, missions: [
      { id: 'chart', title: 'Baca Diagram', phase: 'AMATI → SIMPULKAN', objective: 'Siswa dapat membaca diagram batang dan menyusun kesimpulan.', type: 'choice', visual: 'Apel ████  Pisang ██████', prompt: 'Kesimpulan yang tepat adalah ...', choices: ['Pisang dipilih lebih banyak', 'Apel dipilih lebih banyak', 'Keduanya sama'], answer: 'Pisang dipilih lebih banyak', explain: 'Batang pisang lebih panjang, berarti jumlahnya lebih banyak.' },
      { id: 'grand', title: 'Misi Matematika Besar', phase: 'TANTANGAN', objective: 'Siswa dapat menerapkan perkalian luas dalam masalah desain sederhana.', type: 'input', visual: '12 m × 8 m · 3/4 area', prompt: 'Sebuah taman berukuran 12 m × 8 m. Luasnya ... m².', answer: '96', hint: 'Luas persegi panjang = panjang × lebar.', explain: '12 × 8 = 96 m². Ini langkah pertama merancang taman.' }
    ] }
  ]
};