(() => {
  const content = window.MATH_LAB;
  const screen = document.querySelector('#screen');
  const key = content.storageKey;
  const soundKey = `${key}:sound`;
  let soundOn = localStorage.getItem(soundKey) !== 'false';
  let activeLab = null;
  let activeMission = null;
  let attempts = 0;

  const done = (labId, missionId) => localStorage.getItem(`${key}:done:${labId}:${missionId}`) === 'true';
  const allMissions = () => content.labs.flatMap((lab) => lab.missions.map((mission) => ({ lab, mission })));
  const completed = () => allMissions().filter(({ lab, mission }) => done(lab.id, mission.id)).length;
  const percent = () => Math.round((completed() / allMissions().length) * 100);
  const labPercent = (lab) => Math.round((lab.missions.filter((mission) => done(lab.id, mission.id)).length / lab.missions.length) * 100);
  const nextMission = () => allMissions().find(({ lab, mission }) => !done(lab.id, mission.id));
  const labArt = (lab) => ({ number: '12345', operations: '＋ − × ÷', fraction: '½ ¼ ¾', geometry: '△ □ ○', measurement: '📏 ⏱ ⚖', data: '▂ ▅ █' }[lab.id] || '∑');
  const speak = (text) => { if (soundOn && 'speechSynthesis' in window) { speechSynthesis.cancel(); const voice = new SpeechSynthesisUtterance(text); voice.lang = 'id-ID'; voice.rate = .9; speechSynthesis.speak(voice); } };
  const updateHeader = () => { const mastery = document.querySelector('#masteryTotal'); if (mastery) mastery.textContent = `${percent()}% penguasaan`; const button = document.querySelector('#soundToggle'); if (button) { button.textContent = soundOn ? '🔊' : '🔇'; button.setAttribute('aria-pressed', String(soundOn)); } };
  const progressBar = (value) => `<div class="bar" role="progressbar" aria-valuenow="${value}" aria-valuemin="0" aria-valuemax="100"><span style="width:${value}%"></span></div>`;
  const badgeFor = (lab) => { const value = lab.missions.filter((mission) => done(lab.id, mission.id)).length; return value === lab.missions.length ? '<span class="badge">✓ MISI SELESAI</span>' : `<span class="badge muted">${value}/${lab.missions.length} misi</span>`; };
  const achievementList = () => content.labs.filter((lab) => lab.missions.every((mission) => done(lab.id, mission.id))).map((lab) => `<span class="achievement">🏆 ${lab.badge}</span>`).join('') || '<span class="muted-copy">Selesaikan satu lab untuk membuka pencapaian.</span>';
  const nav = (active = 'home') => `<aside class="sidebar"><a class="brand" href="../../index.html"><span><small>Matematika<br>Kelas 5 SD · Semester 2</small></span></a><nav class="side-nav" aria-label="Navigasi utama"><button class="nav-item ${active === 'home' ? 'active' : ''}" data-nav="home">⌂<span>Beranda</span></button><button class="nav-item ${active === 'practice' ? 'active' : ''}" data-nav="practice">☷<span>Latihan Soal</span></button><button class="nav-item ${active === 'games' ? 'active' : ''}" data-nav="games">✦<span>Permainan</span></button><button class="nav-item ${active === 'achievements' ? 'active' : ''}" data-nav="achievements">♜<span>Pencapaian</span></button><button class="nav-item ${active === 'profile' ? 'active' : ''}" data-nav="profile">●<span>Profil</span></button></nav><button class="nav-item settings-nav" data-nav="settings">⚙<span>Pengaturan</span></button></aside>`;
  const profile = () => `<div class="profile-card"><div class="avatar">😊</div><div><b>Halo, Sahabat Belajar!</b><small>Kelas 5 · Semester 2</small></div><button id="profileSettings" aria-label="Buka pengaturan">⚙</button></div>`;
  const toggleSound = () => { soundOn = !soundOn; localStorage.setItem(soundKey, String(soundOn)); updateHeader(); const settings = document.querySelector('#settingsSound'); if (settings) { settings.textContent = soundOn ? 'Aktif' : 'Mati'; settings.classList.toggle('on', soundOn); } };
  const bindNav = () => document.querySelectorAll('[data-nav]').forEach((button) => button.addEventListener('click', () => renderView(button.dataset.nav)));
  const renderShell = (active, body, headerLeft = '') => { screen.innerHTML = `<div class="app-shell">${nav(active)}<div class="app-main"><header class="topbar"><button class="mobile-menu" id="mobileMenu" aria-label="Buka menu">☰</button>${headerLeft || '<div class="topbar-spacer"></div>'}${profile()}</header>${body}</div></div>`; bindNav(); document.querySelector('#soundToggle')?.addEventListener('click', toggleSound); document.querySelector('#profileSettings')?.addEventListener('click', () => renderView('settings')); document.querySelector('#mobileMenu')?.addEventListener('click', () => document.querySelector('.sidebar').classList.toggle('open')); };
  const renderDashboard = () => {
    activeLab = null;
    activeMission = null;
    updateHeader();
    const next = nextMission();
    const cards = content.labs.map((lab) => `<button class="lab-card ${lab.color}" data-lab="${lab.id}"><span class="lab-number">${lab.code}</span><span class="lab-art">${labArt(lab)}</span><strong>${lab.name}</strong><small>${lab.question}</small><div class="card-progress">${progressBar(labPercent(lab))}<b>${labPercent(lab)}%</b></div>${badgeFor(lab)}<span class="card-arrow">›</span></button>`).join('');
    const mission = next ? `<div class="today-mission"><span class="panel-kicker">🎯 MISI HARI INI</span><div class="mission-art">${labArt(next.lab)}</div><b>${next.mission.title}</b><p>${next.mission.objective}</p><button class="primary-button" id="startMission">▶ Mulai Misi</button></div>` : '<div class="today-mission complete-banner"><b>Semester selesai!</b><span>Semua misi sudah kamu kuasai.</span></div>';
    const body = `<main class="dashboard-page"><section class="welcome"><div class="welcome-copy-wrap"><p class="eyebrow">LABORATORIUM MATEMATIKA DIGITAL</p><h1>Selamat Datang!</h1><h2>Siap menjelajahi dunia matematika hari ini?</h2><p class="welcome-copy">Matematika ada di mana-mana. Yuk, kita temukan keseruannya bersama!</p></div><div class="welcome-summary"><div class="summary-pill"><span>Misi aktif</span><strong>${next ? next.mission.title : 'Selesai'}</strong></div><div class="summary-pill"><span>Penguasaan</span><strong>${percent()}%</strong></div></div><div class="assistant">💡<span>Teman lab siap<br>membantu kamu.</span></div></section><section class="content-layout"><div class="materials-column"><div class="section-heading"><div><span class="panel-kicker">🎯 RUANG BELAJAR</span><h2>Lab Matematika</h2></div><button class="text-button" data-nav="materials">Lihat semua →</button></div><div class="lab-grid">${cards}</div><div class="quote-banner">📖 <span>“Setiap langkah kecil dalam belajar, membawa kamu menuju masa depan yang besar.”</span></div></div><aside class="right-panel"><div class="progress-panel"><div class="section-heading"><span class="panel-kicker">📊 KEMAJUAN BELAJARKU</span><b>${percent()}%</b></div>${progressBar(percent())}<small>${completed()} dari ${allMissions().length} misi selesai</small></div>${mission}<div class="achievement-panel"><div class="section-heading"><span class="panel-kicker">🏆 PENCAPAIAN TERBARU</span><button class="text-button" data-nav="achievements">Lihat semua</button></div><div class="achievements">${achievementList()}</div></div></aside></section></main>`;
    renderShell('home', body);
    const dashboard = document.querySelector('.dashboard-page');
    const contentLayout = dashboard?.querySelector('.content-layout');
    const rightPanel = contentLayout?.querySelector('.right-panel');
    if (dashboard && contentLayout && rightPanel) { dashboard.classList.add('dashboard-with-panel'); dashboard.append(rightPanel); }
    if (dashboard && rightPanel) {
      const welcomeSummary = dashboard.querySelector('.welcome-summary');
      const assistant = dashboard.querySelector('.assistant');
      const asideTools = document.createElement('div');
      asideTools.className = 'aside-welcome-tools';
      if (welcomeSummary) asideTools.append(welcomeSummary);
      if (assistant) asideTools.append(assistant);
      if (asideTools.children.length) rightPanel.prepend(asideTools);
    }
    document.querySelectorAll('.lab-card').forEach((button) => button.addEventListener('click', () => renderLab(button.dataset.lab)));
    document.querySelector('#startMission')?.addEventListener('click', () => renderMission(next.mission.id, next.lab.id));
    document.querySelectorAll('[data-nav="materials"]').forEach((button) => button.addEventListener('click', () => renderView('materials')));
  };
  const renderLab = (labId) => {
    activeLab = content.labs.find((lab) => lab.id === labId);
    const rows = activeLab.missions.map((mission, index) => `<button class="mission-row bg-button" data-mission="${mission.id}"><span class="mission-index">0${index + 1}</span><span><b>${mission.title}</b><small>${mission.phase}</small><em>${mission.objective}</em></span><span class="mission-state">${done(activeLab.id, mission.id) ? '✓ SELESAI' : 'MULAI →'}</span></button>`).join('');
    renderShell('materials', `<main class="inner-page"><div class="lab-heading"><span class="panel-kicker">LAB ${activeLab.code} · ${activeLab.name}</span><h1>${activeLab.question}</h1><p>Amati → Jelajahi → Temukan → Pecahkan → Jelaskan</p><div class="lab-summary">${progressBar(labPercent(activeLab))}<span>${labPercent(activeLab)}% penguasaan · ${activeLab.badge}</span></div></div><div class="mission-list">${rows}</div><div class="challenge-strip"><span class="panel-kicker">TANTANGAN LAB</span><b>${activeLab.challenge.title}</b><span>${activeLab.challenge.prompt}</span></div></main>`, '<button class="back-button" id="back">← Kembali ke Beranda</button>');
    document.querySelector('#back').addEventListener('click', renderDashboard);
    document.querySelectorAll('.mission-row').forEach((button) => button.addEventListener('click', () => renderMission(button.dataset.mission, activeLab.id)));
  };
  const renderMission = (missionId, labId = activeLab.id) => {
    activeLab = content.labs.find((lab) => lab.id === labId);
    activeMission = activeLab.missions.find((mission) => mission.id === missionId);
    attempts = 0;
    const choices = activeMission.choices || [];
    const interaction = activeMission.type === 'input' ? '<form id="answerForm" class="input-form"><input id="answer" aria-label="Jawaban" autocomplete="off" inputmode="text"><button type="submit">PERIKSA</button></form>' : activeMission.type === 'sequence' ? `<div class="sequence"><div class="sequence-choices">${choices.map((choice) => `<button type="button" class="sequence-choice" data-value="${choice}">${choice}</button>`).join('')}</div><p id="sequencePicked">Urutan: —</p><button id="sequenceCheck" class="action-button" type="button">PERIKSA URUTAN</button></div>` : `<div class="choice-grid">${choices.map((choice) => `<button type="button" class="choice" data-value="${choice}">${choice}</button>`).join('')}</div>`;
    renderShell('materials', `<main class="inner-page mission-page"><div class="mission-top"><span class="panel-kicker">${activeMission.phase}</span><span class="mission-step">MISI ${activeLab.missions.indexOf(activeMission) + 1} / ${activeLab.missions.length}</span></div><div class="mission-panel"><div class="mission-visual ${activeLab.color}">${activeMission.visual}</div><div class="objective"><span class="section-label">TUJUAN BELAJAR</span><p>${activeMission.objective}</p></div><h1>${activeMission.prompt}</h1><button class="listen" id="listen">🔊 Dengarkan instruksi</button>${interaction}<button class="hint" id="hint">💡 Petunjuk</button><p class="hint-text" id="hintText"></p><div class="result" id="result" role="status"></div></div></main>`, `<button class="back-button" id="back">← ${activeLab.name}</button>`);
    document.querySelector('#back').addEventListener('click', () => renderLab(activeLab.id));
    document.querySelector('#listen').addEventListener('click', () => speak(`${activeMission.objective}. ${activeMission.prompt}`));
    document.querySelector('#hint').addEventListener('click', () => { attempts += 1; document.querySelector('#hintText').textContent = activeMission.hint || 'Amati representasi dan cari hubungan antar informasi.'; speak(document.querySelector('#hintText').textContent); });
    if (activeMission.type === 'input') document.querySelector('#answerForm').addEventListener('submit', (event) => { event.preventDefault(); checkAnswer(event.currentTarget.elements.answer.value); });
    if (activeMission.type === 'sequence') { const selected = []; document.querySelectorAll('.sequence-choice').forEach((button) => button.addEventListener('click', () => { selected.push(button.dataset.value); button.disabled = true; document.querySelector('#sequencePicked').textContent = `Urutan: ${selected.join(' → ')}`; })); document.querySelector('#sequenceCheck').addEventListener('click', () => checkAnswer(selected)); } else document.querySelectorAll('.choice').forEach((button) => button.addEventListener('click', () => checkAnswer(button.dataset.value)));
  };
  const renderPractice = () => { const rows = allMissions().map(({ lab, mission }) => `<button class="practice-row" data-lab="${lab.id}" data-mission="${mission.id}"><span>${labArt(lab)}</span><span><b>${mission.title}</b><small>${lab.name} · ${mission.objective}</small></span><strong>${done(lab.id, mission.id) ? '✓' : '→'}</strong></button>`).join(''); renderShell('practice', `<main class="inner-page"><span class="panel-kicker">LATIHAN SOAL</span><h1>Latihan Soal</h1><p class="page-intro">Pilih misi untuk berlatih dan periksa pemahamanmu.</p><div class="practice-list">${rows}</div></main>`); document.querySelectorAll('.practice-row').forEach((button) => button.addEventListener('click', () => renderMission(button.dataset.mission, button.dataset.lab))); };
  const renderChallenges = () => { const cards = content.labs.map((lab) => `<button class="challenge-card" data-lab="${lab.id}"><span>${labArt(lab)}</span><b>${lab.challenge.title}</b><small>${lab.challenge.prompt}</small></button>`).join(''); renderShell('games', `<main class="inner-page"><span class="panel-kicker">PERMAINAN BELAJAR</span><h1>Tantangan Matematika</h1><p class="page-intro">Pilih tantangan dan gunakan strategimu.</p><div class="challenge-grid">${cards}</div></main>`); document.querySelectorAll('.challenge-card').forEach((button) => button.addEventListener('click', () => renderLab(button.dataset.lab))); };
  const renderAchievements = () => renderShell('achievements', `<main class="inner-page"><span class="panel-kicker">PENCAPAIAN</span><h1>Pencapaian Belajar</h1><p class="page-intro">Setiap misi yang selesai membuka langkah baru.</p><div class="achievement-page-grid">${content.labs.map((lab) => `<div class="achievement-detail ${lab.missions.every((mission) => done(lab.id, mission.id)) ? 'unlocked' : ''}"><span>${labArt(lab)}</span><b>${lab.badge}</b><small>${labPercent(lab)}% penguasaan · ${lab.name}</small></div>`).join('')}</div></main>`);
  const renderProfile = () => renderShell('profile', `<main class="inner-page"><span class="panel-kicker">PROFIL SISWA</span><h1>Profil Sahabat Belajar</h1><div class="profile-large"><div class="avatar">😊</div><h2>Halo, Sahabat Belajar!</h2><p>Kelas 5 · Semester 2</p><div class="profile-stat"><b>${percent()}%</b><span>Penguasaan Matematika</span></div></div></main>`);
  const renderSettings = () => { renderShell('settings', `<main class="inner-page"><span class="panel-kicker">PENGATURAN</span><h1>Pengaturan Belajar</h1><div class="settings-card"><div><b>Audio instruksi</b><small>Dengarkan petunjuk dan feedback dalam Bahasa Indonesia.</small></div><button class="toggle-button ${soundOn ? 'on' : ''}" id="settingsSound">${soundOn ? 'Aktif' : 'Mati'}</button></div></main>`); document.querySelector('#settingsSound').addEventListener('click', toggleSound); };
  const renderView = (view) => ({ home: renderDashboard, materials: renderDashboard, practice: renderPractice, games: renderChallenges, achievements: renderAchievements, profile: renderProfile, settings: renderSettings }[view] || renderDashboard)();
  const checkAnswer = (value) => { const result = document.querySelector('#result'); const expected = Array.isArray(activeMission.answer) ? activeMission.answer.join('|') : String(activeMission.answer); const actual = Array.isArray(value) ? value.join('|') : String(value).trim(); if (actual === expected) { localStorage.setItem(`${key}:done:${activeLab.id}:${activeMission.id}`, 'true'); result.innerHTML = `<strong>Hebat, benar!</strong><span>${activeMission.explain}</span><button class="action-button" id="continue">BERIKUTNYA</button>`; speak(`Hebat, benar! ${activeMission.explain}`); document.querySelector('#continue').addEventListener('click', () => renderLab(activeLab.id)); } else { result.innerHTML = `<strong class="wrong">Belum tepat.</strong><span>Coba periksa lagi. ${attempts ? activeMission.hint || '' : ''}</span>`; speak('Hampir benar. Coba periksa lagi.'); } };
  renderDashboard();
})();
