window.MATH_LAB = {
  storageKey: 'grade5MathSemester2',
  title: 'Math Lab',
  labs: [
    { id: 'ratio', code: '01', icon: '01', name: 'Lab Rasio dan Perbandingan', color: 'blue', question: 'Kapan strategi perbandingan paling tepat?', badge: 'PENEMU STRATEGI', challenge: { title: 'Buat Rasio', prompt: 'Gunakan perbandingan untuk menjelaskan hubungan dua besaran.' }, missions: [
      { id: 'fraction-to-decimal', title: 'Ubah Pecahan', phase: 'AMATI', objective: 'Siswa dapat mengubah pecahan menjadi desimal dan membandingkan nilainya.', type: 'choice', visual: '3/4 = ?', prompt: '3/4 sama dengan ...', choices: ['0,25', '0,5', '0,75'], answer: '0,75', explain: '3 dibagi 4 sama dengan 0,75.' },
      { id: 'compare-decimals', title: 'Bandingkan Desimal', phase: 'ANALISIS → PILIH STRATEGI', objective: 'Siswa dapat membandingkan desimal dengan alasan yang logis.', type: 'input', visual: '0,7 ; 0,68 ; 0,75', prompt: 'Desimal terbesar di antara ketiga angka tersebut adalah ...', answer: '0,75', hint: 'Bandingkan angka di belakang koma.', explain: '0,75 paling besar karena 75 > 70 > 68.' }
    ] },
    { id: 'fraction', code: '02', icon: '02', name: 'Lab Pecahan dan Desimal', color: 'amber', question: 'Bagaimana pecahan dan desimal membentuk ukuran yang sama?', badge: 'PENJELAJAH PECAHAN', challenge: { title: 'Ubah dan Bandingkan', prompt: 'Ubah bentuk, bandingkan nilai, dan jelaskan strategimu.' }, missions: [
      { id: 'simple-ratio', title: 'Rasio Sederhana', phase: 'AMATI → TEMUKAN', objective: 'Siswa dapat menuliskan rasio sederhana dari dua kelompok benda.', type: 'choice', visual: '4 apel : 6 jeruk', prompt: 'Rasio apel terhadap jeruk adalah ...', choices: ['4:6', '6:4', '2:3'], answer: '4:6', explain: 'Perbandingan jumlah apel dan jeruk adalah 4 banding 6.' },
      { id: 'ratio-problem', title: 'Masalah Rasio', phase: 'PECAHKAN', objective: 'Siswa dapat menyelesaikan masalah rasio dalam konteks nyata.', type: 'input', visual: '8 kotak biru, 12 kotak kuning', prompt: 'Rasio biru terhadap total kotak adalah ...', answer: '2:5', hint: 'Total kotak = 20, lalu sederhanakan 8:20.', explain: '8:20 = 2:5.' }
    ] },
    { id: 'scale', code: '03', icon: '03', name: 'Lab Skala', color: 'green', question: 'Bagaimana skala membantu membandingkan ukuran sebenarnya?', badge: 'PENJELAJAH SKALA', challenge: { title: 'Baca Denah', prompt: 'Gunakan skala untuk menghitung jarak dan ukuran sebenarnya.' }, missions: [
      { id: 'convert-length', title: 'Ubah Satuan Panjang', phase: 'ANALISIS', objective: 'Siswa dapat mengubah satuan panjang yang berbeda dan memilih metode yang tepat.', type: 'choice', visual: '2,5 m = ... cm', prompt: '2,5 m sama dengan ... cm.', choices: ['25 cm', '250 cm', '2500 cm'], answer: '250 cm', explain: '1 m = 100 cm, jadi 2,5 × 100 = 250 cm.' },
      { id: 'solve-volume', title: 'Volume Balok', phase: 'PECAHKAN → JELASKAN', objective: 'Siswa dapat menghitung volume setelah menentukan ukuran yang tepat.', type: 'input', visual: '8 cm × 5 cm × 6 cm', prompt: 'Volume balok itu adalah ... cm³.', answer: '240', hint: 'Volume = p × l × t.', explain: '8 × 5 × 6 = 240 cm³.' }
    ] },
    { id: 'area-volume', code: '04', icon: '04', name: 'Lab Luas dan Volume', color: 'green', question: 'Bagaimana luas dan volume digunakan untuk merancang ruang?', badge: 'PENJELAJAH UKURAN', challenge: { title: 'Rancang Ruang', prompt: 'Hitung luas dan volume untuk memilih solusi yang tepat.' }, missions: [
      { id: 'area-shape', title: 'Luas Bangun', phase: 'AMATI', objective: 'Siswa dapat menghitung luas bangun gabungan sederhana.', type: 'choice', visual: 'persegi 6 m dan persegi panjang 8 m × 3 m', prompt: 'Luas gabungan keduanya adalah ... m².', choices: ['36', '60', '48'], answer: '60', explain: '6 × 6 = 36 dan 8 × 3 = 24, jumlahnya 60.' },
      { id: 'compare-strategy', title: 'Pilih Strategi', phase: 'PILIH STRATEGI → JELASKAN', objective: 'Siswa dapat memilih cara yang paling efisien untuk menyelesaikan keliling dan luas.', type: 'input', visual: 'panjang 14 m, lebar 6 m', prompt: 'Keliling persegi panjang itu adalah ... m.', answer: '40', hint: 'Keliling = 2 × (p + l).', explain: '2 × (14 + 6) = 40 m.' }
    ] },
    { id: 'solid-shapes', code: '05', icon: '05', name: 'Lab Bangun Ruang', color: 'violet', question: 'Bagaimana ciri dan jaring-jaring membantu mengenali bangun ruang?', badge: 'DETEKTIF BANGUN RUANG', challenge: { title: 'Bangun Kotak', prompt: 'Kenali bangun ruang dan jelaskan hubungan ukuran sisinya.' }, missions: [
      { id: 'mode-mean', title: 'Modus dan Rata-rata', phase: 'AMATI → ANALISIS', objective: 'Siswa dapat membaca data dan menentukan modus serta rata-rata.', type: 'choice', visual: '5, 5, 7, 8, 5', prompt: 'Modus dari data tersebut adalah ...', choices: ['5', '7', '8'], answer: '5', explain: 'Angka 5 muncul paling sering.' },
      { id: 'probability', title: 'Peluang Sederhana', phase: 'JELASKAN', objective: 'Siswa dapat menghitung kemungkinan suatu kejadian dari data atau benda.', type: 'input', visual: '6 bola: 2 merah, 4 biru', prompt: 'Peluang mengambil bola merah adalah ...', answer: '1/3', hint: 'Peluang = jumlah kejadian / total kemungkinan.', explain: '2 dari 6 bola merah, jadi 2/6 = 1/3.' }
    ] },
    { id: 'data-probability', code: '06', icon: '06', name: 'Lab Data dan Peluang', color: 'teal', question: 'Bagaimana keputusan terbaik dibuat dari data dan peluang?', badge: 'DETEKTIF DATA', challenge: { title: 'Analisis Hasil', prompt: 'Simpulkan pola, cek kemungkinan, dan jelaskan alasanmu.' }, missions: [
      { id: 'integrated-task', title: 'Masalah Terintegrasi', phase: 'PECAHKAN → JELASKAN', objective: 'Siswa dapat menyelesaikan masalah yang memadukan konsep matematika dalam satu konteks.', type: 'input', visual: '3/5 dari 20 siswa', prompt: 'Jumlah siswa yang memilih kegiatan itu adalah ...', answer: '12', hint: '3/5 × 20 = 12.', explain: '20 dibagi 5 = 4, lalu 4 × 3 = 12.' },
      { id: 'error-check', title: 'Cari Kesalahan', phase: 'VERIFIKASI', objective: 'Siswa dapat memeriksa kebenaran hasil dan memperbaiki alasan yang keliru.', type: 'error', visual: '0,6 + 0,25 = 0,85', prompt: 'Apakah jawaban itu benar?', choices: ['Benar', 'Salah'], answer: 'Benar', hint: '0,60 + 0,25 = 0,85.', explain: '6 persepuluh ditambah 25 per seratus sama dengan 85 per seratus.' }
    ] }
  ]
};